"""Tests for aiguard.mgmt (MgmtClient, explain_api_error, task messages).

Every connection verifies TLS against the CA generated by ``make_test_pki`` and passed as
``ca_file``; nothing here relaxes certificate checks. API keys and passwords are random
values generated at run time and only mean something to the fake server.
"""
from __future__ import annotations

import ast
import base64
import json
import os
import re
import secrets
import socket
import sys
import threading
import time
from pathlib import Path

import pytest

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from fakes import FakeMgmtServer, make_server_cert, make_test_pki  # noqa: E402

from aiguard import redact  # noqa: E402
from aiguard.errors import ConnectError, MgmtApiError, TlsTrustError  # noqa: E402
from aiguard.mgmt import (FORBIDDEN_IP_FIX, MgmtClient, _parse_server,  # noqa: E402
                          api_version_tuple, explain_api_error, release_for_api, task_messages)
from aiguard.runlog import RunLog  # noqa: E402

AIGUARD_DIR = Path(__file__).resolve().parents[2] / "aiguard"


def fake_key() -> str:
    """A throw-away Management API key generated at run time."""
    return "fake-" + secrets.token_hex(16)


# --------------------------------------------------------------------------- fixtures


@pytest.fixture(scope="module")
def pki(tmp_path_factory):
    return make_test_pki(tmp_path_factory.mktemp("mgmt-pki"))


@pytest.fixture
def runlog(aiguard_home):
    log = RunLog(home=aiguard_home)
    yield log
    log.close()


@pytest.fixture
def mgmt(pki, runlog):
    servers = []

    def start(*, client_kw=None, **kw):
        srv = FakeMgmtServer(pki, **kw).start()
        servers.append(srv)
        opts = dict(ca_file=pki.ca_pem_path, timeout=5, log=runlog)
        opts.update(client_kw or {})
        client = MgmtClient("127.0.0.1", srv.port, **opts)
        client.task_poll = 0.01
        return srv, client

    yield start
    for s in servers:
        assert s.errors == [], s.errors[0]
        s.stop()


def log_text(runlog: RunLog) -> str:
    return (Path(runlog.path).read_text(encoding="utf-8") + "\n"
            + Path(runlog.jsonl_path).read_text(encoding="utf-8"))


def assert_not_logged(runlog: RunLog, *values: str) -> None:
    text = log_text(runlog)
    for v in values:
        assert v and v not in text, "secret leaked into the run log"


def sids_seen(srv) -> set:
    return {h.get("X-chkp-sid") for (_c, _p, h) in srv.calls if h.get("X-chkp-sid")}


# --------------------------------------------------------------------------- source rules


def test_owned_modules_stdlib_only_py38_and_no_insecure_calls():
    stdlib = set(getattr(sys, "stdlib_module_names", ())) | {"__future__"}
    banned = re.compile(r"verify\s*=\s*False|CERT_NONE|check_hostname\s*=\s*False|"
                        r"_create_unverified_context|\beval\(|\bexec\(|subprocess|os\.system|pickle")
    for name in ("mgmt.py", "gateways.py", "correlate.py"):
        src = (AIGUARD_DIR / name).read_text(encoding="utf-8")
        tree = ast.parse(src, filename=name, feature_version=(3, 8))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                roots = [a.name.split(".")[0] for a in node.names]
            elif isinstance(node, ast.ImportFrom) and node.level == 0:
                roots = [(node.module or "").split(".")[0]]
            else:
                continue
            for root in roots:
                assert root in stdlib, "%s imports non-stdlib %s" % (name, root)
        assert not banned.search(src), name


# --------------------------------------------------------------------------- login


def test_login_with_api_key_on_sms(mgmt, pki, runlog):
    srv, client = mgmt()
    key = fake_key()
    info = client.login(api_key=key)
    assert info["server_type"] == "SMS" and client.server_type == "SMS"
    assert info["api_version"] == "2.2" and info["release"] == "R82.20"
    assert info["fingerprint_sha256"] == pki.server_sha256 == client.fingerprint
    assert info["fingerprint_sha1"] == pki.server_sha1
    assert info["read_only"] is False and info["domains"] == [] and info["domain"] is None
    assert info["local_ip"] == "127.0.0.1" and info["reported_port"] == srv.port
    assert "sid" not in info and key not in json.dumps(info)
    assert srv.state.logins == 1
    login = srv.calls_for("login")[0]
    assert login["api-key"] == key
    assert login["session-name"] == "aiguard-demo"
    assert login["session-description"] == "AI Guard Demo Kit"
    assert "domain" not in login and "read-only" not in login
    # the sid is used on the next calls and is masked everywhere
    assert client.sid in sids_seen(srv)
    assert redact.redact("sid is " + client.sid) != "sid is " + client.sid
    cmds = client.commands()
    assert {"add-threat-rule", "install-policy", "test-ai-agent-security-api-key"} <= cmds
    assert client.has("show-logs") and not client.has("frobnicate")
    client.commands()
    assert srv.call_names().count("show-commands") == 1  # cached
    sid = client.sid
    assert_not_logged(runlog, key, sid)
    client.logout()
    assert client.sid is None and srv.state.sessions == {}
    assert_not_logged(runlog, key, sid)


def test_login_with_user_password_read_only(mgmt, runlog):
    srv, client = mgmt()
    srv.valid_user, srv.valid_password = "demo-admin", "pw-" + secrets.token_hex(8)
    info = client.login(user="demo-admin", password=srv.valid_password, read_only=True)
    assert info["read_only"] is True and client.read_only is True
    assert info["auth"] == "password" and info["user"] == "demo-admin"
    assert srv.last_call("login")["read-only"] is True
    with pytest.raises(MgmtApiError) as ei:
        client.call("add-host", {"name": "h1", "ip-address": "10.1.1.5"})
    assert ei.value.code == "mgmt.permission_denied"
    assert any("read-only" in f for f in ei.value.fix)
    assert not any("without read-only" in f for f in ei.value.fix)   # aiguard never asks for it
    assert any("Read/Write" in f for f in ei.value.fix) and any("Standby" in f for f in ei.value.fix)
    assert_not_logged(runlog, srv.valid_password, client.sid)


def test_login_reply_port_and_missing_version(mgmt, runlog):
    srv, client = mgmt()
    real = srv._new_session

    def patched(*a, **k):
        reply = real(*a, **k)
        reply["url"] = "https://10.1.1.101:4434/web_api"
        reply.pop("api-server-version", None)
        return reply

    srv._new_session = patched
    info = client.login(api_key=fake_key())
    assert info["reported_port"] == 4434 and client.port == srv.port  # keeps the working port
    assert info["api_version"] == "2.2"  # from show-api-versions
    assert "show-api-versions" in srv.call_names()
    hints = [r for r in runlog.tail(50, level="HINT") if r["component"] == "mgmt"]
    assert hints and hints[-1]["fields"]["reported_port"] == 4434


def test_login_needs_credentials(mgmt):
    srv, client = mgmt()
    with pytest.raises(MgmtApiError) as ei:
        client.login(user="admin")
    assert ei.value.code == "mgmt.no_credentials"
    assert srv.state.logins == 0


def test_mds_domain_uses_login_to_domain_without_extra_login(mgmt, runlog):
    srv, client = mgmt(server_type="MDS")
    key = fake_key()
    info = client.login(api_key=key, domain="lab")
    assert info["server_type"] == "MDS" and info["domain"] == "Lab"
    assert info["domains"] == ["Corp-EMEA", "Lab"]
    assert srv.state.logins == 1
    assert srv.last_call("login-to-domain") == {"domain": "Lab"}
    names = [o["name"] for o in client.show_all("show-gateways-and-servers", {"details-level": "full"})]
    assert "HQ-GW" in names
    assert [d["name"] for d in client.list_domains()] == ["Corp-EMEA", "Lab"]
    client.switch_domain("Corp-EMEA")
    assert client.domain == "Corp-EMEA" and srv.state.logins == 1
    assert client.has("add-threat-rule")
    all_sids = sids_seen(srv)
    client.logout()
    assert srv.state.sessions == {}
    assert_not_logged(runlog, key, *all_sids)


def test_mds_switch_after_system_session_expired_logs_in_again(mgmt):
    srv, client = mgmt(server_type="MDS")
    client.login(api_key=fake_key(), domain="Lab")
    srv.state.sessions.pop(client._system_sid)
    client.switch_domain("Corp-EMEA")
    assert client.domain == "Corp-EMEA" and srv.state.logins == 2
    assert srv.last_call("login")["domain"] == "Corp-EMEA"


def test_login_errors_with_a_domain_are_logged_as_errors(mgmt, runlog):
    srv, client = mgmt(scenario="forbidden_ip", server_type="MDS")
    with pytest.raises(MgmtApiError) as ei:
        client.login(api_key=fake_key(), domain="Lab")
    rec = [r for r in runlog.tail(100) if r["line"] == ei.value.log_line][0]
    assert rec["level"] == "ERROR" and ei.value.code == "mgmt.forbidden_ip"
    srv2, client2 = mgmt(server_type="MDS", client_kw={"ca_file": None})
    with pytest.raises(TlsTrustError) as ei:
        client2.login(api_key=fake_key(), domain="Lab")
    rec = [r for r in runlog.tail(100) if r["line"] == ei.value.log_line][0]
    assert rec["level"] == "ERROR"


def test_mds_without_domain_is_system_data(mgmt):
    srv, client = mgmt(server_type="MDS")
    info = client.login(api_key=fake_key())
    assert info["server_type"] == "MDS" and info["domain"] == "System Data"
    assert [d["name"] for d in client.list_domains()] == ["Corp-EMEA", "Lab"]
    assert srv.call_names().count("show-domains") == 1  # listed once, with the same session
    assert srv.state.logins == 1


def test_mds_wrong_domain_lists_domains_and_keeps_session(mgmt):
    srv, client = mgmt(server_type="MDS")
    with pytest.raises(MgmtApiError) as ei:
        client.login(api_key=fake_key(), domain="Nope")
    err = ei.value
    assert err.what == "Domain 'Nope' was not found on this MDS"
    assert err.code == "mgmt.domain_not_found"
    assert any("Corp-EMEA, Lab" in f for f in err.fix)
    assert err.log_line and err.log_line > 0
    assert srv.state.logins == 1
    # still in System Data: switching costs no login
    client.switch_domain("Lab")
    assert client.domain == "Lab" and srv.state.logins == 1


def test_sms_that_answers_show_domains_is_still_sms(mgmt):
    srv, client = mgmt()
    srv.commands.add("show-domains")  # some SMS builds may answer show-domains
    info = client.login(api_key=fake_key())
    assert info["server_type"] == "SMS" and info["domains"] == []
    assert client.list_domains() == []
    assert "show-session" in srv.call_names()


def test_sms_with_a_domain_is_refused(mgmt):
    srv, client = mgmt()
    with pytest.raises(MgmtApiError) as ei:
        client.login(api_key=fake_key(), domain="Corp-EMEA")
    assert ei.value.code == "mgmt.not_mds"
    assert srv.state.sessions == {} and client.sid is None
    srv2, client2 = mgmt()
    assert client2.login(api_key=fake_key(), domain="SMC User")["domain"] == "SMC User"


def test_forbidden_ip_maps_to_accept_api_calls_fix(mgmt, runlog):
    srv, client = mgmt(scenario="forbidden_ip")
    key = fake_key()
    with pytest.raises(MgmtApiError) as ei:
        client.login(api_key=key)
    err = ei.value
    assert err.what == "Login refused by management (HTTP 403)"
    assert err.code == "mgmt.forbidden_ip" and err.http_status == 403
    assert err.fix == FORBIDDEN_IP_FIX
    assert "Accept API calls from" in err.fix[0] and "api restart" in err.fix[1]
    assert "api status" in err.fix[2]
    assert "You don't have permission to access /web_api/login on this server." in err.server_said
    assert "127.0.0.1" in err.why
    assert err.log_line and err.log_line > 0
    assert_not_logged(runlog, key)


def test_bad_login(mgmt, runlog):
    srv, client = mgmt(scenario="bad_login")
    key = fake_key()
    with pytest.raises(MgmtApiError) as ei:
        client.login(api_key=key)
    err = ei.value
    assert err.what == "Wrong API key or username/password"
    assert err.code == "mgmt.login_failed" and err.api_code == "err_login_failed"
    assert "Authentication to server failed." in err.server_said
    assert "domain" not in err.why
    assert_not_logged(runlog, key)


def test_bad_login_with_domain_mentions_the_domain(mgmt):
    srv, client = mgmt(scenario="bad_login", server_type="MDS")
    with pytest.raises(MgmtApiError) as ei:
        client.login(api_key=fake_key(), domain="Lab")
    err = ei.value
    assert err.code == "mgmt.login_failed"
    assert "'Lab'" in err.why and any("Lab" in f for f in err.fix)
    assert srv.state.logins == 2  # System Data, then the domain directly (domain-only admins)


def test_rate_limited(mgmt):
    srv, client = mgmt(scenario="rate_limited")
    client.login(api_key=fake_key())
    other = MgmtClient("127.0.0.1", srv.port, ca_file=srv.pki.ca_pem_path, log=client.log, timeout=5)
    with pytest.raises(MgmtApiError) as ei:
        other.login(api_key=fake_key())
    err = ei.value
    assert err.code == "mgmt.rate_limited" and err.api_code == "err_too_many_requests"
    assert err.http_status == 429
    assert any("Wait one minute" in f for f in err.fix)
    assert "3" in err.what


def test_locked_objects(mgmt):
    srv, client = mgmt(scenario="locked")
    client.login(api_key=fake_key())
    with pytest.raises(MgmtApiError) as ei:
        client.call("add-threat-rule", {"layer": "Standard Threat Prevention", "position": "top",
                                         "name": "AI Guard Demo"})
    err = ei.value
    assert err.what == "Objects are locked by another session (admin@SmartConsole)"
    assert err.code == "mgmt.object_locked" and err.http_status == 409
    assert "Sessions" in err.fix[0] and "then retry" in err.fix[0]
    assert "admin@SmartConsole" in err.server_said


def test_permission_denied_for_scripts(mgmt):
    srv, client = mgmt(scenario="script_denied")
    client.login(api_key=fake_key())
    with pytest.raises(MgmtApiError) as ei:
        client.call("run-script", {"script-name": "x", "script": "true", "targets": ["HQ-GW"]})
    err = ei.value
    assert err.code == "mgmt.permission_denied" and err.what == "Permission denied: run-script"
    assert any("Run One Time Script" in f for f in err.fix)
    assert err.server_said == "Run one time script permission is required"


def test_unknown_command(mgmt):
    srv, client = mgmt()
    client.login(api_key=fake_key())
    with pytest.raises(MgmtApiError) as ei:
        client.call("frobnicate", {})
    err = ei.value
    assert err.what == "This management version does not support frobnicate"
    assert err.code == "mgmt.command_not_found" and err.api_code == "generic_err_command_not_found"


def test_not_found_validation_and_invalid_parameter(mgmt, runlog):
    srv, client = mgmt()
    client.login(api_key=fake_key())
    with pytest.raises(MgmtApiError) as ei:
        client.call("show-host", {"name": "nope-host"})
    err = ei.value
    assert err.code == "mgmt.not_found" and err.api_code == "generic_err_object_not_found"
    assert "nope-host" in err.what and "show-host" in err.what
    # an existence probe that finds nothing is not an ERROR in the log
    rec = [r for r in runlog.tail(50) if r["line"] == err.log_line][0]
    assert rec["level"] == "INFO"

    rule = {"layer": "Standard Threat Prevention", "position": "top", "name": "R1"}
    client.call("add-threat-rule", rule)
    with pytest.raises(MgmtApiError) as ei:
        client.call("add-threat-rule", rule)
    err = ei.value
    assert err.code == "mgmt.validation" and err.api_code == "err_validation_failed"
    assert "More than one rule named 'R1' exists in layer 'Standard Threat Prevention'." in err.server_said
    assert err.what == "add-threat-rule was rejected: validation failed"

    with pytest.raises(MgmtApiError) as ei:
        client.call("test-ai-agent-security-api-key", {"api-key": "zz", "project-id": "p"})
    err = ei.value
    assert err.code == "mgmt.invalid_parameter"
    assert err.server_said == "api-key must be a 64-character hex string"


def test_session_expired(mgmt):
    srv, client = mgmt()
    client.login(api_key=fake_key())
    sid = client.sid
    srv.state.sessions.clear()
    with pytest.raises(MgmtApiError) as ei:
        client.call("show-session", {})
    assert ei.value.code == "mgmt.session_expired" and ei.value.http_status == 401
    assert sid not in (ei.value.server_said or "")  # masked
    # the client knows it is no longer logged in (status and the UIs say so) ...
    assert client.logged_in is False and client.session_expired is True
    # ... and later calls keep saying why, without sending anything
    n = len(srv.calls)
    with pytest.raises(MgmtApiError) as ei2:
        client.call("show-session", {})
    assert ei2.value.code == "mgmt.session_expired" and len(srv.calls) == n


def test_not_logged_in(mgmt):
    srv, client = mgmt()
    with pytest.raises(MgmtApiError) as ei:
        client.call("show-session", {})
    assert ei.value.code == "mgmt.not_logged_in"


def test_old_version(mgmt):
    srv, client = mgmt(scenario="old_version")
    info = client.login(api_key=fake_key())
    assert info["api_version"] == "2" and info["release"] == "R82"
    assert not client.has("test-ai-agent-security-api-key")


def test_commands_unknown_means_has_everything(mgmt):
    srv, client = mgmt()
    srv.commands.discard("show-commands")
    client.login(api_key=fake_key())
    assert client.commands() == set()
    assert client.has("anything-at-all")


# --------------------------------------------------------------------------- explain_api_error


def test_explain_api_error_cases():
    html = ("<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head><title>403 Forbidden"
            "</title></head><body><h1>Forbidden</h1><p>You don't have permission to access "
            "/web_api/login on this server.</p></body></html>")
    err = explain_api_error("login", 403, html.encode("utf-8"), client_ip="10.1.1.50")
    assert err.what == "Login refused by management (HTTP 403)" and err.fix == FORBIDDEN_IP_FIX
    assert err.server_said == "Forbidden You don't have permission to access /web_api/login on this server."
    assert "10.1.1.50" in err.why

    err = explain_api_error("login", 403, {"code": "generic_error", "message": "API is not accessible"})
    assert err.code == "mgmt.forbidden_ip"

    for status in (400, 403):
        body = {"code": "err_login_failed", "message": "Authentication to server failed."}
        err = explain_api_error("login", status, body, domain="Corp")
        assert err.what == "Wrong API key or username/password"
        assert "domain 'Corp'" in err.why
    assert "domain" not in explain_api_error("login", 400, body).why

    err = explain_api_error("login", 429, {"code": "err_too_many_requests",
                                           "message": "Too many requests in a given amount of time"})
    assert err.code == "mgmt.rate_limited"

    err = explain_api_error("add-threat-rule", 409, {
        "code": "generic_err_object_locked",
        "message": "Object 'Standard Threat Prevention' is locked by another session (bob@SmartConsole)"})
    assert err.what == "Objects are locked by another session (bob@SmartConsole)"

    err = explain_api_error("set-threat-profile", 400, {
        "code": "generic_error", "message": "Validation failed with 2 errors",
        "errors": [{"message": "First problem.", "current-session": True}, {"message": "Second."}]})
    assert err.code == "mgmt.validation" and err.server_said == "First problem.\nSecond."
    assert [e["message"] for e in err.errors] == ["First problem.", "Second."]

    err = explain_api_error("show-threat-profile", 404, {"code": "generic_err_object_not_found",
                                                         "message": "Requested object [P1] not found"},
                            payload={"name": "P1"})
    assert err.what == "Object 'P1' was not found (show-threat-profile)"

    err = explain_api_error("add-host", 403, {"code": "generic_err_permission_denied",
                                              "message": "Permission denied"})
    assert err.code == "mgmt.permission_denied" and "Management API Login" in err.fix[0]

    err = explain_api_error("test-ai-guard-api-key", 404, {"code": "generic_err_command_not_found",
                                                           "message": "Unknown command"})
    assert err.what == "This management version does not support test-ai-guard-api-key"

    err = explain_api_error("show-x", 400, {"code": "weird_code", "message": "Something odd"})
    assert err.what == "show-x failed" and err.server_said == "Something odd"
    assert any("log line" in f for f in err.fix)

    err = explain_api_error("publish", 500, {"code": "generic_internal_error", "message": "boom"})
    assert err.code == "mgmt.server_error" and "HTTP 500" in err.what

    err = explain_api_error("login", 502, "<html><body>Bad Gateway</body></html>")
    assert err.code == "mgmt.server_error" and err.server_said == "Bad Gateway"

    d = err.to_dict()
    assert d["code"] == "mgmt.server_error" and d["command"] == "login"


def test_explain_api_error_redacts_in_to_dict():
    sid = secrets.token_urlsafe(24)
    redact.register_secret(sid)
    err = explain_api_error("show-session", 401, {
        "code": "generic_err_wrong_session_id",
        "message": "Wrong session id [%s]. Session may be expired." % sid})
    assert err.code == "mgmt.session_expired"
    assert sid not in json.dumps(err.to_dict())


# --------------------------------------------------------------------------- tasks


def test_install_policy_success_and_progress(mgmt):
    srv, client = mgmt()
    client.login(api_key=fake_key())
    seen = []
    task = client.install_policy("Standard", ["HQ-GW"], access=False, threat_prevention=True,
                                 progress_cb=lambda pct, status, msg: seen.append((pct, status, msg)))
    assert task["status"] == "succeeded"
    assert "Policy installation succeeded on HQ-GW" in task["messages"]
    rec = srv.state.installs[-1]
    assert rec == {"policy-package": "Standard", "targets": ["HQ-GW"], "access": False,
                   "threat-prevention": True}
    sent = srv.last_call("install-policy")
    assert sent["desktop-security"] is False and sent["qos"] is False
    assert seen and all(isinstance(p, int) for p, _s, _m in seen)
    assert seen[0][1] == "in progress" and seen[-1][:2] == (100, "succeeded")
    assert srv.last_call("show-task")["details-level"] == "full"


def test_install_failure_message_is_extracted(mgmt):
    srv, client = mgmt(scenario="install_fails")
    client.login(api_key=fake_key())
    with pytest.raises(MgmtApiError) as ei:
        client.install_policy("Standard", ["HQ-GW"])
    err = ei.value
    assert err.code == "mgmt.task_failed" and err.task_id
    assert err.what.startswith("Install policy Standard") and err.what.endswith("failed")
    assert ("Rule 1 uses profile AIGuard-Demo. AI Agent Security is not supported by the "
            "software on HQ-GW.") in err.server_said
    assert "Policy installation failed on HQ-GW" in err.server_said
    assert any("R82.20" in f for f in err.fix)
    assert "not installed" in err.state and err.command == "install-policy"
    assert err.log_line and err.log_line > 0
    rec = [r for r in client.log.tail(100) if r["line"] == err.log_line][0]
    assert rec["level"] == "ERROR" and any("R82.20" in f for f in rec["fields"]["fix"])


def test_publish_success_and_failure(mgmt):
    srv, client = mgmt()
    client.login(api_key=fake_key())
    client.call("add-host", {"name": "aiguard-client", "ip-address": "10.1.1.50",
                             "comments": "Created by AI Guard Demo Kit"})
    task = client.publish()
    assert task["status"] == "succeeded" and srv.state.published
    assert any(m.startswith("Published") for m in task["messages"])

    srv2, client2 = mgmt(scenario="publish_fails")
    client2.login(api_key=fake_key())
    with pytest.raises(MgmtApiError) as ei:
        client2.publish()
    err = ei.value
    assert err.what == "Publish failed" and err.code == "mgmt.task_failed"
    assert "Validation failed: the session has invalid objects" in err.server_said
    assert "Nothing was published" in err.state


def test_run_script_output_is_decoded(mgmt):
    srv, client = mgmt()
    client.login(api_key=fake_key())
    reply = client.call("run-script", {"script-name": "AI Guard Demo Kit: test", "script-type": "one time",
                                       "script": "echo ok", "targets": ["HQ-GW"], "timeout": 120})
    task = client.wait_task(reply["task-id"], what="run script")
    assert "ok" in task["messages"]
    assert "Script finished running successfully on HQ-GW" in task["messages"]
    details = {d["source"]: d for d in task["message_details"]}
    assert details["responseMessage"]["target"] == "HQ-GW"


def test_wait_task_survives_a_slow_poll(mgmt, monkeypatch):
    srv, client = mgmt()
    client.login(api_key=fake_key())
    tid = client.call("publish", {})["task-id"]
    real_call = client.call
    state = {"n": 0}

    def flaky(command, payload=None, **kw):
        if command == "show-task" and state["n"] == 0:
            state["n"] += 1
            raise ConnectError("The management server did not answer", code="connect.timeout")
        return real_call(command, payload, **kw)

    monkeypatch.setattr(client, "call", flaky)
    monkeypatch.setattr(time, "sleep", lambda s: None)
    task = client.wait_task(tid, what="publish", poll=0.01)
    assert task["status"] == "succeeded" and state["n"] == 1


def test_wait_task_timeout(mgmt):
    srv, client = mgmt(task_polls=10000)
    client.login(api_key=fake_key())
    tid = client.call("publish", {})["task-id"]
    with pytest.raises(MgmtApiError) as ei:
        client.wait_task(tid, what="publish", timeout=0.3, poll=0.05)
    err = ei.value
    assert err.code == "mgmt.task_timeout" and err.task_id == tid
    assert err.what == "Publish did not finish within 0.3s"


def test_task_messages_parsing():
    task = {
        "status": "failed", "comments": "Policy installation failed on GW1",
        "task-details": [
            {"gatewayName": "GW1", "statusCode": "failed", "statusDescription": "Policy installation failed on GW1",
             "stagesInfo": [{"stage": "Verification", "messages": [
                 {"type": "warn", "message": "Rule 3 hides rule 4"},
                 {"type": "err", "message": "Object X is invalid"},
                 {"type": "info", "message": "Verification started"}]}]},
            {"target": "GW2", "statusCode": "failed",
             "responseError": base64.b64encode(b"confp_cli: not found").decode("ascii"),
             "responseMessage": base64.b64encode(b"partial output").decode("ascii")},
            {"title": "x", "messages": ["plain text message"]},
            "odd string detail",
        ],
    }
    msgs = task_messages(task)
    by_text = {m["text"]: m for m in msgs}
    assert by_text["Object X is invalid"]["level"] == "error"
    assert by_text["Object X is invalid"]["target"] == "GW1"
    assert by_text["Rule 3 hides rule 4"]["level"] == "warning"
    assert by_text["Verification started"]["level"] == "info"
    assert by_text["confp_cli: not found"]["level"] == "error"
    assert by_text["partial output"]["target"] == "GW2"
    assert "plain text message" in by_text and "odd string detail" in by_text
    assert [m["text"] for m in msgs].count("Policy installation failed on GW1") == 1
    assert task_messages({"status": "succeeded"}) == []


# --------------------------------------------------------------------------- transport + TLS


def test_tls_failure_without_ca_file(mgmt):
    srv, client = mgmt(client_kw={"ca_file": None})
    with pytest.raises(TlsTrustError) as ei:
        client.login(api_key=fake_key())
    err = ei.value
    assert err.code == "tls.untrusted"
    assert err.server_said and any("--ca-file" in f for f in err.fix)
    assert srv.state.logins == 0 and srv.calls == []
    assert err.log_line and err.log_line > 0


def test_hostname_mismatch_and_server_name(pki, runlog):
    noip = make_server_cert(pki, san_ip=False)
    with FakeMgmtServer(noip) as srv:
        client = MgmtClient("127.0.0.1", srv.port, ca_file=pki.ca_pem_path, log=runlog, timeout=5)
        with pytest.raises(TlsTrustError) as ei:
            client.login(api_key=fake_key())
        assert ei.value.code == "tls.hostname_mismatch"
        assert any("--server-name" in f for f in ei.value.fix)
        named = MgmtClient("127.0.0.1", srv.port, ca_file=pki.ca_pem_path, server_name="localhost",
                           log=runlog, timeout=5)
        info = named.login(api_key=fake_key())
        assert info["fingerprint_sha256"] == noip.server_sha256
        named.logout()
        assert srv.errors == []


def test_missing_ca_file(tmp_path, runlog):
    with pytest.raises(TlsTrustError) as ei:
        MgmtClient("127.0.0.1", 443, ca_file=str(tmp_path / "nope.pem"), log=runlog)
    assert ei.value.code == "tls.ca_file_missing"


def _free_port() -> int:
    s = socket.socket()
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


def test_connection_refused(pki, runlog):
    client = MgmtClient("127.0.0.1", _free_port(), ca_file=pki.ca_pem_path, log=runlog, timeout=3)
    with pytest.raises(ConnectError) as ei:
        client.login(api_key=fake_key())
    err = ei.value
    assert err.code == "connect.refused"
    assert any("api status" in f for f in err.fix) and any("firewall" in f.lower() for f in err.fix)
    assert any("443" in f or str(client.port) in f for f in err.fix)


def test_timeout_when_server_never_answers(pki, runlog):
    lsock = socket.socket()
    lsock.bind(("127.0.0.1", 0))
    lsock.listen(5)
    accepted = []
    stop = threading.Event()

    def accept():
        lsock.settimeout(0.1)
        while not stop.is_set():
            try:
                conn, _ = lsock.accept()
                accepted.append(conn)  # never answers the TLS handshake
            except OSError:
                continue

    t = threading.Thread(target=accept, daemon=True)
    t.start()
    try:
        client = MgmtClient("127.0.0.1", lsock.getsockname()[1], ca_file=pki.ca_pem_path,
                            log=runlog, timeout=0.5)
        t0 = time.monotonic()
        with pytest.raises(ConnectError) as ei:
            client.login(api_key=fake_key())
        assert ei.value.code == "connect.timeout"
        assert time.monotonic() - t0 < 5
    finally:
        stop.set()
        t.join(2)
        for c in accepted:
            c.close()
        lsock.close()


def test_dns_failure(pki, runlog, monkeypatch):
    def boom(*a, **k):
        raise socket.gaierror(getattr(socket, "EAI_NONAME", 8),
                              "nodename nor servname provided, or not known")

    monkeypatch.setattr(socket, "getaddrinfo", boom)
    client = MgmtClient("mgmt.example.invalid", 443, ca_file=pki.ca_pem_path, log=runlog, timeout=2)
    with pytest.raises(ConnectError) as ei:
        client.login(api_key=fake_key())
    assert ei.value.code == "connect.dns" and "mgmt.example.invalid" in ei.value.what


def test_logout_and_discard_never_raise(mgmt):
    srv, client = mgmt()
    client.login(api_key=fake_key())
    srv.stop()
    client.discard()
    client.logout()
    assert client.sid is None
    client.logout()


# --------------------------------------------------------------------------- helpers


def test_show_all_pages(mgmt):
    srv, client = mgmt(with_cluster=True)
    client.login(api_key=fake_key())
    objs = client.show_all("show-gateways-and-servers", {"details-level": "full"}, limit=2)
    assert [o["name"] for o in objs] == ["HQ-GW", "LAB-CL", "LAB-CL-m1", "LAB-CL-m2", "SMS"]
    pages = srv.calls_for("show-gateways-and-servers")
    assert [(p["limit"], p["offset"]) for p in pages] == [(2, 0), (2, 2), (2, 4)]


def test_show_logs_query(mgmt):
    srv, client = mgmt()
    srv.add_log(src="10.1.1.50", dst="api.openai.com", action="Prevent")
    srv.add_log(src="10.1.1.99", dst="api.openai.com", action="Prevent")
    client.login(api_key=fake_key())
    logs = client.show_logs("src:10.1.1.50")
    assert len(logs) == 1 and logs[0]["src"] == "10.1.1.50"
    assert srv.state.log_queries[-1] == {"filter": "src:10.1.1.50", "time-frame": "last-hour",
                                         "max-logs-per-request": 100, "type": "logs"}


def test_keepalive(mgmt):
    srv, client = mgmt()
    client.login(api_key=fake_key())
    client.keepalive()
    assert srv.call_names()[-1] == "keepalive"


def test_secrets_never_reach_the_log_files(mgmt, runlog):
    srv, client = mgmt()
    key = fake_key()
    ai_key = secrets.token_hex(32)
    client.login(api_key=key)
    client.call("add-threat-profile", {"name": "AIGuard-Demo", "comments": "Created by AI Guard Demo Kit",
                                       "ai-agent-security": True, "ai-agent-security-api-key": ai_key,
                                       "ai-agent-security-settings": {"project-id": "project-1"}})
    with pytest.raises(MgmtApiError):
        client.call("frobnicate", {"api-key": key})
    srv.state.sessions.clear()  # the next call is answered with "Wrong session id [<sid>]"
    with pytest.raises(MgmtApiError):
        client.call("show-session", {})
    pw = "pw-" + secrets.token_hex(10)
    other = MgmtClient("127.0.0.1", srv.port, ca_file=srv.pki.ca_pem_path, log=runlog, timeout=5)
    other.login(user="someone", password=pw)
    sids = sids_seen(srv)
    assert len(sids) == 2
    other.logout()
    client.logout()
    assert_not_logged(runlog, key, ai_key, pw, *sids)


def test_parse_server_and_versions():
    assert _parse_server("10.0.0.1", 443) == ("10.0.0.1", 443, "")
    assert _parse_server("10.0.0.1:4434", 443) == ("10.0.0.1", 4434, "")
    assert _parse_server("https://mgmt.lab.test:4434/web_api", 443) == ("mgmt.lab.test", 4434, "")
    assert _parse_server("https://tenant.example/abc-123/", 443) == ("tenant.example", 443, "/abc-123")
    assert _parse_server("[fd00::1]:8443", 443) == ("fd00::1", 8443, "")
    with pytest.raises(ConnectError):
        _parse_server("  ", 443)
    assert release_for_api("2.2") == "R82.20" and release_for_api("1.9.1") == "R81.20 JHF T43+"
    assert release_for_api("2.0") == "R82" and release_for_api("9.9") is None
    assert api_version_tuple("2.0.1") == (2, 0, 1) and api_version_tuple(None) == ()


# --------------------------------------------------------------------------- review fixes


def test_login_payload_and_password_never_reach_logs_or_errors(mgmt, runlog):
    srv, client = mgmt()
    pw = "Secret-pass-" + secrets.token_hex(2) + "c9b7"
    srv.valid_user, srv.valid_password = "aiguard-admin", pw
    client.login(user="aiguard-admin", password=pw)
    text = log_text(runlog)
    assert pw not in text and pw[-4:] not in text          # not even the tail
    assert "login ok" in text and '"password"' not in text
    login = [r for r in runlog.tail(200) if r.get("msg") == "login ok"]
    payload = login[-1]["fields"]["payload"]
    assert "user" not in payload and "password" not in payload
    assert payload["session-timeout"] == 3600
    client.logout()
    wrong = "Wrong-pass-77QZ"
    with pytest.raises(MgmtApiError) as ei:
        client.login(user="aiguard-admin", password=wrong)
    data = ei.value.to_dict()
    assert "payload" not in data["details"]
    assert "77QZ" not in json.dumps(data) and "77QZ" not in log_text(runlog)


def test_install_fix_for_unsupported_data_types(mgmt):
    lab = ("Layer 'Network': Rule 2 (AI) - The following Data Types are not supported: 'PCI - "
           "Credit Card Numbers - 20 or more' ... refer to sk116272. Policy verification failed.")
    fix = MgmtClient._install_fix(lab, ["GW"], "Standard")
    assert fix[0].startswith("Remove the data types the server lists from rule 2 (AI) in layer "
                             "Network") and "sk116272" in fix[0]
    assert not any("upgrade" in f for f in fix)
    old = "Rule 1 uses profile P. AI Agent Security is not supported by the software on GW."
    assert MgmtClient._install_fix(old, ["GW"], "Standard")[0].startswith(
        "AI Agent Security needs R82.20 on the gateway")
    assert not MgmtClient._install_fix("Policy verification failed: object X has a bad "
                                       "version comment", ["GW"], "Standard")[0].startswith(
        "AI Agent Security needs R82.20")


def test_outbound_certificate_prefers_the_default_one(mgmt, pki):
    from aiguard.mgmt import show_outbound_certificate

    srv, client = mgmt(scenario="outbound_needs_name")
    srv.outbound_certs.insert(0, {"name": "AAA-old", "uid": "uid-old", "is-default": False})
    client.login(api_key=fake_key())
    cert = show_outbound_certificate(client)
    assert cert["name"] == "Outbound Certificate" and cert["is-default"] is True
    assert srv.last_call("show-outbound-inspection-certificates")["details-level"] == "full"
    # no certificate marked default: the first one, with a warning in the log
    for c in srv.outbound_certs:
        c["is-default"] = False
    assert show_outbound_certificate(client)["name"] == "AAA-old"


def test_relogin_after_the_server_dropped_the_session(mgmt):
    srv, client = mgmt(server_type="MDS")
    client.login(api_key=fake_key(), domain="Lab")
    srv.state.sessions.clear()
    with pytest.raises(MgmtApiError):
        client.call("show-session", {})
    assert client.can_relogin()
    info = client.relogin()
    assert info["domain"] == "Lab" and client.logged_in and not client.session_expired
    assert client.call("show-session", {})["domain"]["name"] == "Lab"
    client.logout()
    assert not client.can_relogin()


def test_wait_task_failure_carries_start_time_and_messages(mgmt):
    srv, client = mgmt(scenario="install_fails")
    client.login(api_key=fake_key())
    with pytest.raises(MgmtApiError) as ei:
        client.install_policy("Standard", ["HQ-GW"])
    d = ei.value.details
    assert isinstance(d["start_posix"], int) and d["install_submitted"] is True
    assert d["install"] == {"package": "Standard", "targets": ["HQ-GW"], "access": False,
                            "threat_prevention": True}
    assert any(m["level"] == "error" and m["source"] == "stagesInfo"
               for m in d["message_details"])
