"""Tests for the aiguard foundation: errors, redact, paths, runlog, tlsutil, state.

All secret-looking values are generated at test time. TLS tests use a CA
generated by the ``tls_pki`` fixture and a local server on 127.0.0.1;
verification is never relaxed.
"""

from __future__ import annotations

import ast
import datetime as _datetime
import hashlib
import http.client
import importlib
import json
import os
import re
import secrets
import ssl
import string
import sys
import threading
import urllib.parse
from pathlib import Path
from types import SimpleNamespace

import pytest

from aiguard import __version__, errors, paths, redact, runlog, state, tlsutil
from aiguard.errors import (AiguardError, ApprovalError, ConnectError, LakeraError,
                            MgmtApiError, PlanError, TlsTrustError)
from aiguard.redact import mask_secret, redact as do_redact, redact_obj, register_secret

AIGUARD_DIR = Path(__file__).resolve().parents[2] / "aiguard"
OWNED_FILES = ["__init__.py", "__main__.py", "errors.py", "redact.py", "paths.py",
               "runlog.py", "tlsutil.py", "state.py"]


def rand_alnum(n: int, alphabet: str = string.ascii_letters + string.digits) -> str:
    return "".join(secrets.choice(alphabet) for _ in range(n))


# =========================================================================== package


def test_version_and_lazy_main():
    assert __version__ == "1.0.0"
    # Importing __main__ must not import or run the CLI.
    mod = importlib.import_module("aiguard.__main__")
    assert callable(mod._run)


def test_owned_modules_are_stdlib_only_and_py38_syntax():
    stdlib = set(getattr(sys, "stdlib_module_names", ())) | {"__future__"}
    for name in OWNED_FILES:
        src = (AIGUARD_DIR / name).read_text(encoding="utf-8")
        tree = ast.parse(src, filename=name, feature_version=(3, 8))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                roots = [a.name.split(".")[0] for a in node.names]
            elif isinstance(node, ast.ImportFrom) and node.level == 0:
                roots = [(node.module or "").split(".")[0]]
            else:
                continue
            for root in roots:
                if stdlib:
                    assert root in stdlib, "%s imports non-stdlib %s" % (name, root)


def test_owned_modules_follow_security_policy():
    forbidden = [
        r"verify\s*=\s*False", r"CERT_NONE", r"check_hostname\s*=\s*False",
        r"_create_unverified_context", r"\beval\s*\(", r"\bexec\s*\(", r"subprocess",
        r"os\.system", r"\bpickle\b", r"shell\s*=\s*True",
    ]
    for name in OWNED_FILES:
        src = (AIGUARD_DIR / name).read_text(encoding="utf-8")
        for pat in forbidden:
            assert not re.search(pat, src), "%s matches forbidden pattern %s" % (name, pat)


# =========================================================================== errors


def test_aiguard_error_fields_and_defaults():
    err = AiguardError("Login refused")
    assert str(err) == "Login refused"
    assert err.what == "Login refused"
    assert err.code == "aiguard.error"
    assert err.fix == [] and err.details == {} and err.log_line is None
    assert err.server_said is None and err.why is None and err.state is None

    err2 = AiguardError("x", code="custom.code", server_said="s", why="w", fix=("a", "b"),
                        state="st", details={"k": 1})
    d = err2.to_dict()
    for key in ("type", "code", "what", "server_said", "why", "fix", "state", "details",
                "log_line"):
        assert key in d
    assert d["code"] == "custom.code" and d["fix"] == ["a", "b"] and d["type"] == "AiguardError"
    json.dumps(d)  # serialisable


def test_error_subclasses_and_codes():
    for cls in (MgmtApiError, TlsTrustError, ConnectError, LakeraError, PlanError,
                ApprovalError):
        err = cls("boom")
        assert isinstance(err, AiguardError)
        assert err.code and err.code != ""
        assert cls("boom", code="my.code").code == "my.code"


def test_error_to_dict_is_redacted():
    secret = "sk-ant-" + rand_alnum(40)
    register_secret(secret)
    err = MgmtApiError(
        "login failed for key %s" % secret,
        command="login", http_status=400, api_code="err_login_failed",
        server_said='{"message": "bad key %s"}' % secret,
        why="because %s" % secret, fix=["retry without %s" % secret],
        state="nothing", details={"password": "pw-" + rand_alnum(12), "note": secret},
        errors=[{"message": "x %s" % secret}], task_id="t-1",
    )
    d = err.to_dict()
    blob = json.dumps(d)
    assert secret not in blob
    assert d["command"] == "login" and d["http_status"] == 400
    assert d["api_code"] == "err_login_failed" and d["task_id"] == "t-1"
    assert d["details"]["password"].startswith("****")
    assert d["warnings"] == [] and d["blocking_errors"] == []


# =========================================================================== redact


def test_mask_secret_rules():
    assert mask_secret(None) == ""
    assert mask_secret("") == ""
    assert mask_secret("abc") == "****"
    assert mask_secret("abcdefg") == "****"
    tail = rand_alnum(4)
    assert mask_secret("sk-ant-" + rand_alnum(30) + tail) == "sk-ant-****" + tail
    assert mask_secret("sk-" + rand_alnum(30) + tail) == "sk-****" + tail
    assert mask_secret("lk_" + rand_alnum(30) + tail) == "lk_****" + tail
    assert mask_secret("AKIA" + rand_alnum(12, string.ascii_uppercase) + "WXYZ") == "AKIA****WXYZ"
    assert mask_secret("ghp_" + rand_alnum(30) + tail) == "ghp_****" + tail
    assert mask_secret("xoxb-" + rand_alnum(30) + tail) == "xoxb-****" + tail
    hex_key = secrets.token_hex(32)
    assert len(hex_key) == 64
    assert mask_secret(hex_key) == "****" + hex_key[-4:]
    # A short value after a prefix does not reveal most of itself.
    assert mask_secret("sk-abcdefg") == "****defg"
    # Masked values are fixed points.
    for v in ("****", "****abcd", "sk-****abcd", "sk-ant-****abcd", "AKIA****WXYZ"):
        assert mask_secret(v) == v


def test_registered_secret_never_appears_after_redact():
    secret = 'pw"' + rand_alnum(20) + "/&+x"
    register_secret(secret)
    texts = [
        secret,
        "login with %s now" % secret,
        json.dumps({"payload": {"value": secret}}),
        json.dumps({"x": "prefix-%s-suffix" % secret}),
        "https://example.invalid/?q=" + urllib.parse.quote(secret, safe=""),
        "form: " + urllib.parse.quote_plus(secret, safe=""),
        "line1\n%s\nline3" % secret,
    ]
    for text in texts:
        out = do_redact(text)
        assert secret not in out
        assert "****" in out
    obj = {"a": [{"b": secret}], "c": ("x", secret)}
    assert secret not in json.dumps(redact_obj(obj))
    # forget_secret stops masking plain words again
    word = "Harmless" + rand_alnum(6)
    register_secret(word)
    assert word not in do_redact("say %s" % word)
    redact.forget_secret(word)
    assert do_redact("say %s" % word) == "say %s" % word


def test_register_secret_ignores_none_and_short():
    register_secret(None)
    register_secret("abc")
    assert do_redact("abc is fine") == "abc is fine"


def test_registry_is_thread_safe():
    values = ["Secret%02d-%s" % (i, rand_alnum(12)) for i in range(40)]
    errors_seen = []

    def worker(chunk):
        try:
            for v in chunk:
                register_secret(v)
                assert v not in do_redact("x %s y" % v)
        except AssertionError as exc:  # pragma: no cover - failure path
            errors_seen.append(exc)

    threads = [threading.Thread(target=worker, args=(values[i::8],)) for i in range(8)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    assert not errors_seen
    blob = do_redact(" ".join(values))
    assert not any(v in blob for v in values)


def test_redact_obj_masks_sensitive_keys_nested():
    sid = rand_alnum(43)
    api_key = secrets.token_hex(32)
    pw = "pw-" + rand_alnum(14)
    bearer = rand_alnum(40)
    original = {
        "login": {"user": "admin", "password": pw, "api-key": api_key},
        "session": [{"sid": sid, "uid": "1234-uid"}],
        "headers": {"X-chkp-sid": sid, "Authorization": "Bearer " + bearer,
                    "Content-Type": "application/json", "Cookie": "a=" + rand_alnum(20)},
        "profile": {"ai-agent-security-api-key": api_key, "name": "AIGuard-Demo",
                    "ai-agent-security": True},
        "lakera_api_key": api_key,
        "apiKey": api_key,
        "client_secret": {"inner": rand_alnum(20), "flag": True, "none": None},
        "passed": 3, "bypass": "yes", "masked_key": "sk-****abcd",
        "api_key_env": "LAKERA_KEY", "token_count": 17,
    }
    snapshot = json.dumps(original, sort_keys=True)
    out = redact_obj(original)
    assert json.dumps(original, sort_keys=True) == snapshot  # deep copy, input untouched
    blob = json.dumps(out)
    for s in (sid, api_key, pw, bearer):
        assert s not in blob
    assert out["login"]["user"] == "admin"
    assert out["login"]["password"] == "****"     # passwords: no tail (human-chosen, short)
    assert out["login"]["api-key"] == "****" + api_key[-4:]
    assert out["session"][0]["sid"] == mask_secret(sid)
    assert out["session"][0]["uid"] == "1234-uid"
    assert out["headers"]["X-chkp-sid"].startswith("****")
    assert out["headers"]["Authorization"].startswith("****")
    assert out["headers"]["Content-Type"] == "application/json"
    assert out["headers"]["Cookie"].startswith("****")
    assert out["profile"]["name"] == "AIGuard-Demo"
    assert out["profile"]["ai-agent-security"] is True
    assert out["client_secret"]["flag"] is True and out["client_secret"]["none"] is None
    assert out["client_secret"]["inner"].startswith("****")
    assert out["passed"] == 3 and out["bypass"] == "yes"
    assert out["masked_key"] == "sk-****abcd"
    assert out["api_key_env"] == "LAKERA_KEY" and out["token_count"] == 17
    assert redact_obj(out) == out  # fixed point


def test_is_sensitive_key():
    yes = ["password", "Password", "pass", "api-key", "api_key", "apiKey", "X-API-Key",
           "x-chkp-sid", "X-Chkp-Sid", "sid", "authorization", "Proxy-Authorization",
           "cookie", "Set-Cookie", "secret", "client_secret", "access_token", "token",
           "ai-agent-security-api-key", "lakera_api_key", "private_key", "new-password"]
    no = ["passed", "bypass", "inside", "sidebar", "masked_key", "key", "uid", "session-uid",
          "api_key_env", "token_count", "lakera_api_key_configured", "auth", "tokens", ""]
    for k in yes:
        assert redact.is_sensitive_key(k), k
    for k in no:
        assert not redact.is_sensitive_key(k), k


def test_bearer_and_auth_headers_masked():
    token = "eyJ" + rand_alnum(60)
    for text in ("Authorization: Bearer %s" % token,
                 '{"Authorization": "Bearer %s"}' % token,
                 "curl -H 'authorization: bearer %s' https://x" % token,
                 "sent Bearer %s to provider" % token,
                 "Authorization: Basic %s" % rand_alnum(24)):
        out = do_redact(text)
        assert token not in out
        assert "****" in out
        assert do_redact(out) == out
    sid = rand_alnum(43)
    assert sid not in do_redact("X-chkp-sid: %s" % sid)
    assert sid not in do_redact('{"sid": "%s", "url": "https://mgmt/web_api"}' % sid)
    assert do_redact('{"sid": "%s"}' % sid) == '{"sid": "%s"}' % mask_secret(sid)


def test_aws_example_style_keys_masked():
    access = "AKIA" + rand_alnum(16, string.ascii_uppercase + string.digits)
    secret_key = rand_alnum(40, string.ascii_letters + string.digits + "/+")
    text = ("[default]\naws_access_key_id = %s\naws_secret_access_key = %s\n"
            % (access, secret_key))
    out = do_redact(text)
    assert access not in out and secret_key not in out
    assert "AKIA****" + access[-4:] in out
    env = do_redact("AWS_SECRET_ACCESS_KEY=%s" % secret_key)
    assert secret_key not in env
    js = do_redact(json.dumps({"SecretAccessKey": secret_key, "AccessKeyId": access}))
    assert secret_key not in js and access not in js


def test_provider_key_formats_and_blocks_masked():
    keys = [
        "sk-ant-api03-" + rand_alnum(60),
        "sk-proj-" + rand_alnum(48),
        "sk-" + rand_alnum(48),
        "lk_" + rand_alnum(32),
        "ghp_" + rand_alnum(36),
        "xoxb-" + rand_alnum(12, string.digits) + "-" + rand_alnum(24),
        "AIza" + rand_alnum(35),
    ]
    for key in keys:
        out = do_redact("the key is %s." % key)
        assert key not in out, key
        assert do_redact(out) == out
    long_hex = secrets.token_hex(32)
    for text in ("api-key: %s" % long_hex, "lakera token=%s" % long_hex,
                 '"password": "%s"' % long_hex, "my_secret: '%s'" % long_hex,
                 "password=%s&user=admin" % rand_alnum(12)):
        out = do_redact(text)
        assert "****" in out, text
        assert do_redact(out) == out
    body = "\n".join(rand_alnum(64) for _ in range(3))
    pem = "-----BEGIN PRIVATE KEY-----\n%s\n-----END PRIVATE KEY-----" % body
    out = do_redact("key:\n" + pem + "\ndone")
    assert body.splitlines()[0] not in out and out.endswith("done")
    trunc = do_redact("-----BEGIN EC PRIVATE KEY-----\n" + body)
    assert body.splitlines()[0] not in trunc
    url = "https://admin:%s@mgmt.lab.invalid/web_api" % rand_alnum(16)
    assert url.split(":")[2].split("@")[0] not in do_redact(url)


def test_normal_prose_untouched():
    prose = [
        "The gateway blocked the prompt at 10:15:02.",
        "SmartConsole > Manage & Settings > Blades > Management API > Advanced Settings > "
        "Accept API calls from: All IP addresses that can be used for GUI clients",
        "Publish, then on the management server run: api restart",
        "Password policy: see the Permission Profiles page.",
        "Bearer authentication is used by the provider.",
        "auth=api-key server=10.1.1.101 port=443 domain=null status=pass",
        '{"status": "pass", "auth": "password", "passed": 3, "uid": "7b1c2d"}',
        "fingerprint AB:CD:EF:01:23:45:67:89 plan_id=0a1b2c3d4e5f",
        "task-id 01234567-89ab-cdef-0123-456789abcdef succeeded",
        "Threat profile AIGuard-Demo with AI Agent Security on (project project-123)",
        "Install policy on HQ-GW: succeeded with warnings.",
        "Use --server-name <name in certificate> and --ca-file mgmt.pem",
        "Ünïcödé text ✓ stays the same",
        "",
    ]
    for text in prose:
        assert do_redact(text) == text, text
    assert do_redact(None) == ""
    assert redact_obj({"a": [1, 2.5, None, True, "text"]}) == {"a": [1, 2.5, None, True, "text"]}


# =========================================================================== paths


def test_paths_env_and_default(tmp_path, monkeypatch):
    home = tmp_path / "custom-home"
    monkeypatch.setenv("AIGUARD_HOME", str(home))
    assert paths.aiguard_home() == home
    assert not home.exists()  # not created by aiguard_home()
    assert paths.logs_dir(create=False) == home / "logs"
    assert not (home / "logs").exists()
    assert paths.logs_dir() == home / "logs" and (home / "logs").is_dir()
    assert paths.reports_dir() == home / "reports" and (home / "reports").is_dir()
    assert paths.state_path() == home / "state.json"
    assert paths.config_path() == home / "config.json"
    other = tmp_path / "explicit"
    assert paths.logs_dir(other) == other / "logs" and (other / "logs").is_dir()
    monkeypatch.setenv("AIGUARD_HOME", "   ")
    assert paths.aiguard_home() == Path.home() / ".aiguard"
    monkeypatch.delenv("AIGUARD_HOME")
    assert paths.aiguard_home() == Path.home() / ".aiguard"


# =========================================================================== runlog

HUMAN_RE = re.compile(r"^\d\d:\d\d:\d\d\.\d{3} (DEBUG|INFO |WARN |ERROR|HINT )  \S")


def _read_lines(path: Path):
    return path.read_text(encoding="utf-8").split("\n")[:-1]


def _read_jsonl(path: Path):
    return [json.loads(l) for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]


def test_runlog_files_and_first_line(aiguard_home):
    log = runlog.RunLog()
    try:
        assert log.path.parent == aiguard_home / "logs"
        assert re.match(r"^\d{4}-\d{2}-\d{2}_\d{6}\.log$", log.path.name)
        assert log.jsonl_path == log.path.with_suffix(".jsonl")
        first = _read_lines(log.path)[0]
        assert re.match(r"^\d{4}-\d{2}-\d{2}T\d\d:\d\d:\d\d\S* INFO   session   start "
                        r"host=\S+ user=\S+ ver=1\.0\.0 os=\S", first), first
        rec = _read_jsonl(log.jsonl_path)[0]
        assert rec["line"] == 1 and rec["component"] == "session" and rec["msg"] == "start"
        assert rec["fields"]["ver"] == __version__
        if os.name == "posix":
            assert (log.path.stat().st_mode & 0o777) == 0o600
    finally:
        log.close()


def test_runlog_name_collisions_get_suffix(aiguard_home, monkeypatch):
    class FixedDatetime(_datetime.datetime):
        @classmethod
        def now(cls, tz=None):
            return cls(2026, 9, 30, 10, 15, 0, 123000, tzinfo=tz)

    fake = SimpleNamespace(datetime=FixedDatetime, date=_datetime.date,
                           time=_datetime.time, timezone=_datetime.timezone)
    monkeypatch.setattr(runlog, "_dt", fake)
    logs = [runlog.RunLog(aiguard_home) for _ in range(3)]
    try:
        names = [l.path.name for l in logs]
        assert names == ["2026-09-30_101500.log", "2026-09-30_101500_2.log",
                         "2026-09-30_101500_3.log"]
        assert [l.jsonl_path.name for l in logs][2] == "2026-09-30_101500_3.jsonl"
        web = runlog.RunLog(aiguard_home, prefix="web")
        assert web.path.name == "web_2026-09-30_101500.log"
        web.close()
    finally:
        for l in logs:
            l.close()


def test_runlog_event_format_line_numbers_and_multiline(aiguard_home):
    log = runlog.RunLog()
    try:
        n1 = log.info("mgmt", "login ok", server="10.1.1.1", ms=120)
        n2 = log.event("warn", "preflight", "check failed",
                       detail="first line\nsecond line\nthird line", blocking=True)
        n3 = log.hint("cli", "next step", fix=["run api status", "retry"])
        n4 = log.error("engine", "multi\nline message")
        n5 = log.debug("probe", "done", note="has spaces here")
        assert (n1, n2) == (2, 3)
        assert n3 == 6  # n2 used three lines
        assert n4 == 8  # n3 used two lines (fix list)
        assert n5 == 10
        lines = _read_lines(log.path)
        assert lines[n1 - 1].endswith("INFO   mgmt      login ok server=10.1.1.1 ms=120")
        assert HUMAN_RE.match(lines[n1 - 1])
        assert len(lines[n1 - 1].split("login ok")[0]) == 30
        assert lines[n2 - 1].endswith(
            "WARN   preflight check failed blocking=true detail=first line")
        assert lines[n2] == " " * 30 + "second line"
        assert lines[n2 + 1] == " " * 30 + "third line"
        assert "fix=1. run api status" in lines[n3 - 1]
        assert lines[n3] == " " * 30 + "2. retry"
        assert lines[n4 - 1].endswith("ERROR  engine    multi")
        assert lines[n4] == " " * 30 + "line message"
        assert 'note="has spaces here"' in lines[n5 - 1]
        records = _read_jsonl(log.jsonl_path)
        by_line = {r["line"]: r for r in records}
        assert by_line[n2]["level"] == "WARN"
        assert by_line[n2]["fields"]["detail"] == "first line\nsecond line\nthird line"
        assert by_line[n3]["fields"]["fix"] == ["run api status", "retry"]
        for r in records:
            assert set(r) == {"ts", "level", "component", "msg", "fields", "line"}
            assert lines[r["line"] - 1]  # points at a real line
        assert log.lines == len(lines)
    finally:
        log.close()


def test_runlog_redacts_everything(aiguard_home):
    secret = "sk-" + rand_alnum(40)
    register_secret(secret)
    pw = "pw-" + rand_alnum(16)
    unregistered_sid = rand_alnum(43)
    log = runlog.RunLog()
    try:
        log.info("mgmt", "sending key %s" % secret, key=secret, headers={
            "X-chkp-sid": unregistered_sid, "Authorization": "Bearer " + secret},
            body={"password": pw, "user": "admin"}, path=Path("/tmp/x"),
            dump='{"sid": "%s"}' % unregistered_sid)
        log.error("mgmt", "auth failed", password=pw)
        log.close()
        for f in (log.path, log.jsonl_path):
            content = f.read_text(encoding="utf-8")
            for s in (secret, pw, unregistered_sid):
                assert s not in content, f.name
        rec = _read_jsonl(log.jsonl_path)[1]
        assert rec["fields"]["body"]["user"] == "admin"
        assert rec["fields"]["path"] == "/tmp/x"
    finally:
        log.close()


def test_runlog_thread_safe_8_threads(aiguard_home):
    log = runlog.RunLog()
    per_thread = 150
    results = {}

    def worker(tid):
        got = []
        for i in range(per_thread):
            if i % 10 == 0:
                got.append((log.info("t%d" % tid, "multi %d" % i, text="a\nb"), tid, i, 2))
            else:
                got.append((log.info("t%d" % tid, "event %d" % i, i=i), tid, i, 1))
        results[tid] = got

    threads = [threading.Thread(target=worker, args=(t,)) for t in range(8)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    log.close()
    all_events = [e for got in results.values() for e in got]
    assert len(all_events) == 8 * per_thread
    starts = sorted(e[0] for e in all_events)
    assert len(set(starts)) == len(starts)
    lines = _read_lines(log.path)
    expected_lines = 1 + sum(e[3] for e in all_events) + 1  # start + events + end
    assert len(lines) == expected_lines
    for line_no, tid, i, width in all_events:
        line = lines[line_no - 1]
        assert HUMAN_RE.match(line), line
        assert (" t%d " % tid) in line and ("multi %d" % i if width == 2 else "event %d" % i) in line
        if width == 2:
            assert lines[line_no] == " " * 30 + "b"
    records = _read_jsonl(log.jsonl_path)
    assert len(records) == 8 * per_thread + 2
    assert [r["line"] for r in records] == sorted(r["line"] for r in records)


def test_runlog_cannot_be_forged_by_server_text(aiguard_home):
    log = runlog.RunLog()
    try:
        n = log.warn("mgmt", "server said",
                     body="ok\r\n12:00:00.000 INFO   fake      forged x\x1b[31mred")
        after = log.info("mgmt", "next")
        lines = _read_lines(log.path)
        assert after == n + 3
        assert lines[n] == " " * 30 + "12:00:00.000 INFO   fake      forged"
        assert lines[n + 1].startswith(" " * 30 + "x") and "\x1b" not in lines[n + 1]
        for line in lines[1:]:
            assert HUMAN_RE.match(line) or line.startswith(" " * 30), line
    finally:
        log.close()


def test_runlog_tail_filters(aiguard_home):
    log = runlog.RunLog()
    try:
        for i in range(5):
            log.info("mgmt", "info %d" % i)
        log.warn("preflight", "warn 1")
        log.error("mgmt", "error 1")
        log.error("probe", "error 2")
        log.hint("cli", "hint 1")
        assert [r["msg"] for r in log.tail(3)] == ["error 1", "error 2", "hint 1"]
        assert [r["msg"] for r in log.tail(level="ERROR")] == ["error 1", "error 2"]
        assert [r["msg"] for r in log.tail(level="warn,error")] == ["warn 1", "error 1", "error 2"]
        assert [r["msg"] for r in log.tail(level=["WARNING"])] == ["warn 1"]
        assert [r["msg"] for r in log.tail(component="mgmt", level="ERROR")] == ["error 1"]
        assert len(log.tail(component="mgmt")) == 6
        assert log.tail(0) == []
        assert log.tail(2, component="nope") == []
    finally:
        log.close()


def test_runlog_exception_sets_log_line(aiguard_home):
    secret = secrets.token_hex(32)
    register_secret(secret)
    log = runlog.RunLog()
    try:
        log.info("x", "before")
        err = MgmtApiError("Login refused by management (HTTP 403)", command="login",
                           http_status=403, server_said="denied for %s" % secret,
                           why="API accepts calls from the management server only",
                           fix=["SmartConsole > Manage & Settings > Blades > Management API",
                                "api restart"], state="Nothing was changed")
        line = log.exception(err, "mgmt")
        assert err.log_line == line == 3
        lines = _read_lines(log.path)
        assert "ERROR  mgmt      Login refused by management (HTTP 403)" in lines[line - 1]
        assert "fix=1. SmartConsole" in lines[line - 1]
        assert any(l.startswith(" " * 30 + "2. api restart") for l in lines)
        assert err.to_dict()["log_line"] == line
        rec = [r for r in _read_jsonl(log.jsonl_path) if r["line"] == line][0]
        assert rec["level"] == "ERROR" and rec["fields"]["code"] == "mgmt.error"
        assert rec["fields"]["http_status"] == 403
        assert secret not in log.path.read_text(encoding="utf-8")
        try:
            raise KeyError("boom")
        except KeyError as exc:
            line2 = log.exception(exc, "engine")
            assert getattr(exc, "log_line", line2) == line2
        rec2 = [r for r in _read_jsonl(log.jsonl_path) if r["line"] == line2][0]
        assert "Traceback" in rec2["fields"]["traceback"]
    finally:
        log.close()


def test_runlog_echo_and_close(aiguard_home):
    seen = []
    log = runlog.RunLog(echo=lambda level, text: seen.append((level, text)))
    log.warn("cli", "hello ✓ café", n=1)
    assert seen[-1][0] == "WARN" and "hello ✓ café n=1" in seen[-1][1]

    def broken(level, text):
        raise RuntimeError("ui gone")

    log.echo = broken
    assert log.info("cli", "still logged") > 0
    log.close()
    log.close()  # idempotent
    lines = _read_lines(log.path)
    assert "session   end" in lines[-1]
    assert "hello ✓ café" in log.path.read_text(encoding="utf-8")
    # events after close are appended, not lost
    n = log.info("late", "after close")
    assert _read_lines(log.path)[n - 1].endswith("after close")
    log.close()


def test_latest_log(tmp_path):
    home = tmp_path / "h"
    assert runlog.latest_log(home) is None
    assert not (home / "logs").exists()
    a = runlog.RunLog(home)
    a.close()
    b = runlog.RunLog(home)
    b.close()
    os.utime(a.path, (1_000_000_000, 1_000_000_000))
    assert runlog.latest_log(home) == b.path


# =========================================================================== tlsutil


def test_make_context_defaults(tls_pki):
    ctx = tlsutil.make_context()
    assert ctx.minimum_version == ssl.TLSVersion.TLSv1_2
    assert ctx.verify_mode == ssl.CERT_REQUIRED and ctx.check_hostname is True
    ctx2 = tlsutil.make_context(str(tls_pki.ca_file))
    subjects = [dict(x[0] for x in c["subject"]).get("commonName") for c in ctx2.get_ca_certs()]
    assert "AIGuard Test Root CA" in subjects


def test_make_context_bad_ca_file(tmp_path):
    with pytest.raises(TlsTrustError) as ei:
        tlsutil.make_context(str(tmp_path / "missing.pem"))
    err = ei.value
    assert err.code == "tls.ca_file_missing"
    assert any("--ca-file" in f for f in err.fix)
    garbage = tmp_path / "garbage.pem"
    garbage.write_text("this is not a certificate\n")
    with pytest.raises(TlsTrustError) as ei2:
        tlsutil.make_context(str(garbage))
    assert ei2.value.code == "tls.ca_file_invalid"
    assert any("openssl x509" in f or "--ca-file" in f for f in ei2.value.fix)
    with pytest.raises(TlsTrustError) as ei3:
        tlsutil.make_context(str(tmp_path))
    assert ei3.value.code == "tls.ca_file_invalid"


def _get(conn):
    conn.request("GET", "/")
    resp = conn.getresponse()
    return resp.status, resp.read()


def test_verified_connection_success_with_ca_file(tls_pki, https_server):
    srv = https_server()
    conn = tlsutil.VerifiedHTTPSConnection(srv.host, srv.port,
                                           context=tlsutil.make_context(str(tls_pki.ca_file)),
                                           timeout=5)
    try:
        assert _get(conn) == (200, b"ok")
        peer = conn.peer
        assert peer is not None
        assert peer == tlsutil.peer_summary(conn.sock) == tlsutil.peer_summary(conn)
        assert peer["sha256"] == tls_pki.default.sha256
        assert peer["sha1"] == tls_pki.default.sha1
        assert re.match(r"^([0-9A-F]{2}:){31}[0-9A-F]{2}$", peer["sha256"])
        assert re.match(r"^([0-9A-F]{2}:){19}[0-9A-F]{2}$", peer["sha1"])
        assert peer["issuer_cn"] == "AIGuard Test Root CA"
        assert peer["issuer_org"] == "AIGuard Test Lab"
        assert peer["subject_cn"] == "localhost"
        assert "IP:127.0.0.1" in peer["san"] and "DNS:localhost" in peer["san"]
        assert peer["san_ip"] == ["127.0.0.1"] and peer["san_dns"] == ["localhost"]
        assert re.match(r"^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\dZ$", peer["not_after"])
        assert peer["tls_version"] in ("TLSv1.2", "TLSv1.3")
        assert peer["cipher"]
        assert peer["peer_ip"] == "127.0.0.1" and peer["local_ip"] == "127.0.0.1"
        assert not tlsutil.is_public_issuer(peer["issuer_org"], peer["issuer_cn"])
    finally:
        conn.close()


def test_verified_connection_fails_without_ca_file(https_server):
    srv = https_server()
    conn = tlsutil.VerifiedHTTPSConnection(srv.host, srv.port, context=tlsutil.make_context(),
                                           timeout=5)
    with pytest.raises(ssl.SSLCertVerificationError) as ei:
        conn.connect()
    assert conn.sock is None
    e = ei.value
    err = tlsutil.trust_error(e, srv.host, "management", port=srv.port)
    assert isinstance(err, TlsTrustError)
    assert err.code == "tls.untrusted"
    assert err.server_said == e.verify_message
    assert any("--ca-file" in f for f in err.fix)
    assert any("api fingerprint" in f for f in err.fix)
    assert any("--server-name" in f for f in err.fix)  # connecting by IP
    assert err.state and "Nothing was changed" in err.state
    prov = tlsutil.trust_error(e, "api.openai.com", "provider")
    assert prov.code == "tls.untrusted"
    assert "HTTPS Inspection" in prov.why
    assert any("HTTPS Inspection > Step 2" in f for f in prov.fix)
    # the provider CA is --outbound-ca (--ca-file is the management server's CA)
    assert any("--outbound-ca" in f for f in prov.fix)
    assert not any("--ca-file" in f for f in prov.fix)
    json.dumps(err.to_dict())


def test_hostname_mismatch_when_cert_lacks_ip_san(tls_pki, https_server):
    srv = https_server(cert="noip")
    ctx = tlsutil.make_context(str(tls_pki.ca_file))
    conn = tlsutil.VerifiedHTTPSConnection("127.0.0.1", srv.port, context=ctx, timeout=5)
    with pytest.raises(ssl.SSLCertVerificationError) as ei:
        conn.connect()
    e = ei.value
    assert "mismatch" in e.verify_message.lower()
    err = tlsutil.trust_error(e, "127.0.0.1", "management", port=srv.port,
                              ca_file=str(tls_pki.ca_file))
    assert err.code == "tls.hostname_mismatch"
    assert err.server_said == e.verify_message  # verbatim
    text = " ".join([err.what, err.why] + err.fix)
    for needle in ("sk164382", "--server-name", "api fingerprint", "Subject Alternative Name",
                   "self-signed", "--ca-file"):
        assert needle in text, needle
    assert err.details["category"] == "ip_mismatch"

    # Same server, verified against the name that IS in the certificate.
    conn2 = tlsutil.VerifiedHTTPSConnection("127.0.0.1", srv.port, context=ctx,
                                            server_hostname="localhost", timeout=5)
    try:
        assert _get(conn2) == (200, b"ok")
        assert conn2.peer["san"] == ["DNS:localhost"]
        assert conn2.peer["subject_cn"] == "127.0.0.1"
        assert conn2.peer["sha256"] == tls_pki.noip.sha256
    finally:
        conn2.close()


def _fake_verify_error(message, code):
    e = ssl.SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate "
                                        "verify failed: %s" % message)
    e.verify_message = message
    e.verify_code = code
    return e


def test_trust_error_branches():
    dns = tlsutil.trust_error(
        _fake_verify_error("Hostname mismatch, certificate is not valid for 'mgmt.lab'.", 62),
        "mgmt.lab", "management")
    assert dns.code == "tls.hostname_mismatch"
    assert "mgmt.lab" in dns.what and "--server-name" in " ".join(dns.fix)
    assert "sk164382" in " ".join(dns.fix) and "api fingerprint" in " ".join(dns.fix)

    for msg, code, expect in [
        ("certificate has expired", 10, "tls.expired"),
        ("Basic Constraints of CA cert not marked critical", 89, "tls.strict"),
        ("self-signed certificate", 18, "tls.untrusted"),
        ("unable to get local issuer certificate", 20, "tls.untrusted"),
        ("something odd", 99, "tls.error"),
    ]:
        for purpose in ("management", "provider"):
            err = tlsutil.trust_error(_fake_verify_error(msg, code), "10.0.0.5", purpose)
            assert err.code == expect, (msg, purpose)
            assert err.what and err.why and err.fix and err.state
            assert err.server_said == msg

    prov = tlsutil.trust_error(
        _fake_verify_error("Hostname mismatch, certificate is not valid for 'api.openai.com'.",
                           62), "api.openai.com", "provider")
    assert prov.code == "tls.hostname_mismatch" and "proxy" in prov.why

    not_tls = tlsutil.trust_error(ssl.SSLError(1, "[SSL: WRONG_VERSION_NUMBER] wrong version "
                                                  "number"), "10.0.0.5", "management", port=4434)
    assert not_tls.code == "tls.not_tls" and "4434" in not_tls.what

    with_ca = tlsutil.trust_error(_fake_verify_error("self-signed certificate", 18),
                                  "10.0.0.5", "management", ca_file="/x/ca.pem")
    assert "/x/ca.pem" in with_ca.why


def test_is_public_issuer():
    base = ("google trust services", "digicert", "let's encrypt", "sectigo", "cloudflare",
            "globalsign", "amazon", "microsoft", "entrust", "godaddy", "baltimore",
            "identrust", "comodo", "usertrust", "isrg", "starfield", "certainly")
    extra = ("baltimore", "globalsign", "digicert", "sectigo", "let's encrypt", "isrg",
             "google trust services", "amazon", "microsoft", "entrust", "godaddy", "starfield",
             "identrust", "usertrust", "comodo", "certainly", "cloudflare", "buypass",
             "actalis", "ssl.com", "harica", "e-tugra", "certum", "quovadis", "swisssign",
             "telia", "wisekey", "trustwave", "secom", "t-systems", "d-trust")
    for name in base + extra:
        assert name in tlsutil.PUBLIC_CA_ORGS, name
        assert tlsutil.is_public_issuer(name.upper() + " Inc", ""), name
    assert tlsutil.is_public_issuer("Google Trust Services", "WR1")
    assert tlsutil.is_public_issuer("Let\u2019s Encrypt", "R11")
    assert tlsutil.is_public_issuer("", "Amazon RSA 2048 M02")
    assert tlsutil.is_public_issuer("GoDaddy.com, Inc.", "Go Daddy Secure CA")
    assert tlsutil.is_public_issuer("SSL Corporation", "SSL.com RSA SSL subCA")
    assert not tlsutil.is_public_issuer("Check Point", "HQ-GW Outbound Inspection CA")
    assert not tlsutil.is_public_issuer("AIGuard Test Lab", "AIGuard Test Root CA")
    assert not tlsutil.is_public_issuer("Amazonian Lab", "Internal CA")
    assert not tlsutil.is_public_issuer(None, None)


def test_verified_connection_requires_context():
    with pytest.raises(TypeError):
        tlsutil.VerifiedHTTPSConnection("127.0.0.1", 443, context=None)  # type: ignore[arg-type]
    conn = tlsutil.VerifiedHTTPSConnection("127.0.0.1", 443, context=tlsutil.make_context(),
                                           server_hostname="  ")
    assert conn.server_hostname is None
    assert isinstance(conn, http.client.HTTPSConnection)


def test_fingerprint_format():
    fp = tlsutil.fingerprint(b"abc", "sha256")
    assert fp == ":".join("%02X" % b for b in hashlib.sha256(b"abc").digest())
    assert tlsutil.fingerprint(b"", "sha1") == ""


# =========================================================================== state


def test_state_default_path_and_last(aiguard_home):
    st = state.State()
    assert st.path == aiguard_home / "state.json"
    assert st.last() == {}
    assert st.list_rollbacks() == []
    st.set_last(server="10.1.1.101", port=443, domain=None, gateway="HQ-GW",
                ca_file=Path("/certs/mgmt.pem"), server_name="mgmt.lab", auth="api-key",
                user="admin")
    last = st.last()
    assert last["server"] == "10.1.1.101" and last["port"] == 443
    assert last["ca_file"] == "/certs/mgmt.pem" and last["auth"] == "api-key"
    assert "domain" not in last and "updated_at" in last
    st.set_last(gateway=None, auth="password")
    last = state.State().last()  # fresh instance reads the file
    assert "gateway" not in last and last["auth"] == "password"
    raw = json.loads((aiguard_home / "state.json").read_text(encoding="utf-8"))
    assert raw["version"] == 1 and "rollbacks" in raw
    if os.name == "posix":
        assert (st.path.stat().st_mode & 0o777) == 0o600


def test_state_refuses_secrets(aiguard_home):
    st = state.State()
    st.set_last(server="10.1.1.101")
    before = st.path.read_bytes()
    pw = "pw-" + rand_alnum(16)
    api_key = secrets.token_hex(32)
    with pytest.raises(ValueError):
        st.set_last(password=pw)
    with pytest.raises(ValueError):
        st.set_last(api_key=api_key)
    register_secret(api_key)
    with pytest.raises(ValueError) as ei:
        st.set_last(user=api_key)  # a value that redact() would change
    assert api_key not in str(ei.value)
    with pytest.raises(ValueError):
        st.set_last(note="Authorization: Bearer %s" % rand_alnum(40))
    with pytest.raises(ValueError):
        st.add_rollback({"server": "10.1.1.101", "steps": [
            {"command": "add-threat-profile",
             "payload": {"ai-agent-security-api-key": secrets.token_hex(32)}}]})
    with pytest.raises(ValueError):
        st.add_rollback({"server": "x", "sid": rand_alnum(43)})
    assert st.path.read_bytes() == before  # nothing written
    # Masked display payloads are fine.
    rid = st.add_rollback({"server": "10.1.1.101", "steps": [
        {"command": "add-threat-profile",
         "payload": {"ai-agent-security-api-key": mask_secret(secrets.token_hex(32)),
                     "ai-agent-security": True}}]})
    assert st.get_rollback(rid)["steps"][0]["payload"]["ai-agent-security"] is True
    with pytest.raises(ValueError):
        st.mark_rollback(rid, note="token=%s" % rand_alnum(40))
    assert st.get_rollback(rid)["status"] == "recorded"


def test_state_rollbacks(aiguard_home, monkeypatch):
    st = state.State()
    ids = []
    for i in range(3):
        ids.append(st.add_rollback({"server": "10.1.1.101" if i < 2 else "10.9.9.9",
                                    "objects": [{"type": "threat-profile", "uid": "u%d" % i}],
                                    "rollback": [{"command": "delete-threat-profile",
                                                  "payload": {"name": "AIGuard-Demo"}}]}))
    for rid in ids:
        assert re.match(r"^[0-9a-f]{6}$", rid)
    assert len(set(ids)) == 3
    listed = st.list_rollbacks()
    assert [r["id"] for r in listed] == ids  # oldest first
    assert all(r["status"] == "recorded" and r["created_at"] for r in listed)
    got = st.get_rollback(ids[1].upper())
    assert got["objects"][0]["uid"] == "u1"
    got["objects"][0]["uid"] = "changed"  # copies only
    assert st.get_rollback(ids[1])["objects"][0]["uid"] == "u1"
    assert st.get_rollback("ffffff" if "ffffff" not in ids else "000000") is None
    assert st.get_rollback(None) is None
    updated = st.mark_rollback(ids[1], status="rolled-back", id="hijack")
    assert updated["status"] == "rolled-back" and updated["id"] == ids[1]
    assert st.mark_rollback("nope00") is None
    assert st.latest_rollback()["id"] == ids[2]
    assert st.latest_rollback(server="10.1.1.101")["id"] == ids[0]  # ids[1] is rolled back
    assert st.latest_rollback(server="10.1.1.101", include_done=True)["id"] == ids[1]
    assert st.latest_rollback(server="nowhere") is None

    # Id collisions are retried.
    seq = iter([ids[0], ids[0], "abc123"])
    real_token_hex = secrets.token_hex

    def fake_token_hex(n=None):
        return next(seq) if n == 3 else real_token_hex(n)

    monkeypatch.setattr(state.secrets, "token_hex", fake_token_hex)
    assert st.add_rollback({"server": "s"}) == "abc123"


def test_state_atomic_write(aiguard_home, monkeypatch):
    st = state.State()
    st.set_last(server="first")
    before = st.path.read_bytes()

    def boom(src, dst):
        raise OSError("disk full")

    monkeypatch.setattr(state.os, "replace", boom)
    with pytest.raises(OSError):
        st.set_last(server="second")
    monkeypatch.undo()
    assert st.path.read_bytes() == before
    leftovers = [p.name for p in aiguard_home.iterdir() if p.name.endswith(".tmp")]
    assert leftovers == []
    assert st.last()["server"] == "first"


def test_state_corrupt_file_is_moved_aside(aiguard_home):
    p = aiguard_home / "state.json"
    p.write_text("{not json", encoding="utf-8")
    st = state.State(p)
    assert st.last() == {}
    assert any(x.name.startswith("state.json.corrupt-") for x in aiguard_home.iterdir())
    st.set_last(server="ok")
    assert st.last()["server"] == "ok"


def test_state_threads(aiguard_home):
    st = state.State()
    out = []
    lock = threading.Lock()

    def worker(i):
        rid = st.add_rollback({"server": "srv", "n": i})
        with lock:
            out.append(rid)

    threads = [threading.Thread(target=worker, args=(i,)) for i in range(8)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    assert len(set(out)) == 8
    assert sorted(r["id"] for r in st.list_rollbacks()) == sorted(out)


def test_check_secret_free_messages_hide_values():
    value = "sk-" + rand_alnum(40)
    with pytest.raises(ValueError) as ei:
        state.check_secret_free({"a": [{"b": value}]})
    assert value not in str(ei.value)
    assert '["a"][0]["b"]' in str(ei.value)
    state.check_secret_free({"a": [{"b": "plain"}], "passed": 2, "flag": True})


def test_passwords_are_masked_without_a_tail():
    from aiguard.redact import (forget_secret, is_password_key, mask_secret, redact, redact_obj,
                                register_secret)
    pw = "Winter2026"
    assert mask_secret(pw) == "****2026" and mask_secret(pw, keep_tail=False) == "****"
    assert mask_secret("", keep_tail=False) == ""
    assert redact_obj({"password": pw, "mgmt_password": pw, "passwd": pw, "pwd": pw,
                       "passphrase": pw, "api-key": "k" * 20 + "WXYZ"}) == {
        "password": "****", "mgmt_password": "****", "passwd": "****", "pwd": "****",
        "passphrase": "****", "api-key": "****WXYZ"}
    assert is_password_key("password") and is_password_key("new-password")
    assert not is_password_key("api-key") and not is_password_key("password_file")
    text = 'login payload={"user": "aiguard-admin", "password": "Wrong-pass-77QZ"} password=%s' % pw
    out = redact(text)
    assert "77QZ" not in out and "2026" not in out and out.count("****") == 2
    assert redact(out) == out                    # still a fixed point
    secret = "Secret-pass-c9b7"
    register_secret(secret, keep_tail=False)
    try:
        assert redact("typed %s here" % secret) == "typed **** here"
        register_secret(secret)                  # a later normal registration stays strict
        assert "c9b7" not in redact(secret)
    finally:
        forget_secret(secret)
    assert redact(secret) == secret              # forgotten again


def test_latest_rollback_skips_discarded_points(aiguard_home):
    st = state.State()
    a = st.add_rollback({"server": "10.1.1.101", "summary": "installed", "status": "installed"})
    b = st.add_rollback({"server": "10.1.1.101", "summary": "publish failed"})
    st.mark_rollback(b, status="discarded")
    assert st.latest_rollback(server="10.1.1.101")["id"] == a
    assert st.latest_rollback(server="10.1.1.101", include_done=True)["id"] == b
    c = st.add_rollback({"server": "10.1.1.101", "domain": "Lab", "summary": "domain"})
    assert st.latest_rollback(server="10.1.1.101", domain="Corp")["id"] == a
    assert st.latest_rollback(server="10.1.1.101", domain="lab")["id"] == c


def test_state_writers_on_one_file_never_lose_updates(aiguard_home):
    import threading as _th
    path = aiguard_home / "state.json"
    a, b = state.State(path), state.State(path)      # e.g. two web sessions, one home
    ids = []

    def add():
        for i in range(60):
            ids.append(a.add_rollback({"server": "s", "summary": "p%d" % i}))

    def last():
        for i in range(60):
            b.set_last(server="s", gateway="GW%d" % i)

    threads = [_th.Thread(target=add), _th.Thread(target=last)]
    for t in threads:
        t.start()
    for t in threads:
        t.join(30)
    kept = {r["id"] for r in state.State(path).list_rollbacks()}
    assert len(ids) == 60 and set(ids) <= kept
    assert state.State(path).last()["gateway"] == "GW59"
    assert (aiguard_home / "state.json.lock").exists()
