"""Tests for aiguard.plan and aiguard.templates (build / apply / rollback).

The fake management server is reached over verified TLS with the CA generated by
``make_test_pki`` (passed as ``ca_file``); nothing here relaxes certificate checks. The
Management API key and the AI Agent Security key are random values generated at run time.
"""
from __future__ import annotations

import ast
import json
import os
import re
import secrets
import sys
from pathlib import Path

import pytest

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from fakes import (LAB_DATA_TYPES_ERROR, FakeMgmtServer, make_cluster,  # noqa: E402
                   make_gateway, make_test_pki)

from aiguard import redact  # noqa: E402
from aiguard.errors import ApprovalError, PlanError  # noqa: E402
from aiguard.mgmt import MgmtClient  # noqa: E402
from aiguard.plan import (Plan, PlanOptions, apply_plan, build_plan,  # noqa: E402
                          client_host_name, compute_plan_id, render_value, rollback)
from aiguard.runlog import RunLog  # noqa: E402
from aiguard.state import State  # noqa: E402
from aiguard.templates import list_templates, load_template, validate_template  # noqa: E402

AIGUARD_DIR = Path(__file__).resolve().parents[2] / "aiguard"
CLIENT_IP = "10.1.1.50"
HOST = "aiguard-client-10-1-1-50"
LAYER = "Standard Threat Prevention"
MARK = "Created by AI Guard Demo Kit"
CONFP = "confp_cli set -p firewall.ipv4.prompt_injection.prompt_injection_moderated_content_enable"


def guard_key() -> str:
    """A throw-away 64-hex AI Agent Security key generated at run time."""
    return secrets.token_hex(32)


def project_id() -> str:
    return "proj-" + secrets.token_hex(4)


# --------------------------------------------------------------------------- fixtures


@pytest.fixture(scope="module")
def pki(tmp_path_factory):
    return make_test_pki(tmp_path_factory.mktemp("plan-pki"))


@pytest.fixture
def runlog(aiguard_home):
    log = RunLog(home=aiguard_home)
    yield log
    log.close()


@pytest.fixture
def state(aiguard_home):
    return State(aiguard_home / "state.json")


@pytest.fixture
def connect(pki, runlog):
    servers = []

    def start(*, read_only=False, **kw):
        srv = FakeMgmtServer(pki, **kw).start()
        servers.append(srv)
        client = MgmtClient("127.0.0.1", srv.port, ca_file=pki.ca_pem_path, timeout=5, log=runlog)
        client.task_poll = 0.01
        client.login(api_key="fake-" + secrets.token_hex(12), read_only=read_only)
        srv.reset_calls()
        return srv, client

    yield start
    for s in servers:
        assert s.errors == [], s.errors[0]
        s.stop()


def opts(**kw) -> PlanOptions:
    base = dict(gateway="HQ-GW", client_ip=CLIENT_IP, lakera_project_id="proj-demo")
    base.update(kw)
    return PlanOptions(**base)


def names(srv, skip=("show-task",)):
    return [c for c in srv.call_names() if c not in skip]


def log_text(runlog: RunLog) -> str:
    return (Path(runlog.path).read_text(encoding="utf-8") + "\n"
            + Path(runlog.jsonl_path).read_text(encoding="utf-8"))


def read_only_calls(srv) -> list:
    return [c for c in srv.call_names() if not (c.startswith("show-") or c.startswith("test-"))]


# --------------------------------------------------------------------------- source rules


def test_owned_modules_stdlib_only_py38_and_no_insecure_calls():
    stdlib = set(getattr(sys, "stdlib_module_names", ())) | {"__future__"}
    banned = re.compile(r"verify\s*=\s*False|CERT_NONE|check_hostname\s*=\s*False|"
                        r"_create_unverified_context|\beval\(|\bexec\(|subprocess|os\.system|pickle")
    for path in (AIGUARD_DIR / "plan.py", AIGUARD_DIR / "templates" / "__init__.py"):
        src = path.read_text(encoding="utf-8")
        tree = ast.parse(src, filename=str(path), feature_version=(3, 8))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                roots = [a.name.split(".")[0] for a in node.names]
            elif isinstance(node, ast.ImportFrom) and node.level == 0:
                roots = [(node.module or "").split(".")[0]]
            else:
                continue
            for root in roots:
                assert root in stdlib, "%s imports non-stdlib %s" % (path.name, root)
        assert not banned.search(src), path.name


# --------------------------------------------------------------------------- templates


def test_builtin_templates_load_as_package_data():
    from importlib import resources

    assert resources.files("aiguard.templates").joinpath("ai-agent-security.json").is_file()
    ids = [t["id"] for t in list_templates()]
    assert "ai-agent-security" in ids and "https-inspection" in ids
    t = load_template("ai-agent-security")
    assert t["_source"] == "builtin" and t["min_api_version"] == "2.2"
    assert [s["id"] for s in t["steps"]] == ["client_host", "profile", "rule", "publish", "install",
                                            "moderation"]
    assert load_template("https-inspection.json")["id"] == "https-inspection"
    t["steps"].clear()  # a copy: the next load is unaffected
    assert load_template("ai-agent-security")["steps"]


@pytest.mark.parametrize("bad", ["../ai-agent-security", "AI Agent", "", "nope", "a/b"])
def test_template_names_are_restricted(bad):
    with pytest.raises(PlanError) as ei:
        load_template(bad)
    assert ei.value.code == "plan.template"


def test_template_validation_rules():
    good = load_template("ai-agent-security")
    good.pop("_source")
    validate_template(good)
    bad = json.loads(json.dumps(good))
    bad["steps"].insert(0, dict(bad["steps"][-1]))  # script before publish
    bad["steps"][0]["id"] = "early"
    with pytest.raises(PlanError, match="after publish"):
        validate_template(bad)
    bad = json.loads(json.dumps(good))
    bad["steps"][1].pop("exists")
    with pytest.raises(PlanError, match="exists"):
        validate_template(bad)
    bad = json.loads(json.dumps(good))
    bad["steps"][2]["id"] = "profile"
    with pytest.raises(PlanError, match="twice"):
        validate_template(bad)
    bad = json.loads(json.dumps(good))
    bad["steps"][0]["when"] = "sometimes"
    with pytest.raises(PlanError, match="when"):
        validate_template(bad)


def test_lab_override_in_home(connect, aiguard_home, runlog):
    tpl = load_template("ai-agent-security")
    tpl.pop("_source")
    tpl["variables"]["profile_name"] = "Lab-Profile"
    (aiguard_home / "templates").mkdir()
    (aiguard_home / "templates" / "ai-agent-security.json").write_text(json.dumps(tpl), encoding="utf-8")
    assert load_template("ai-agent-security")["_source"].endswith("ai-agent-security.json")
    srv, client = connect()
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    assert plan.step("profile").display_payload["name"] == "Lab-Profile"
    # an explicit option still wins over the lab default
    plan = build_plan(client, opts(profile_name="Mine"), secrets={"lakera_api_key": guard_key()},
                      log=runlog)
    assert plan.step("profile").display_payload["name"] == "Mine"
    (aiguard_home / "templates" / "ai-agent-security.json").write_text("{not json", encoding="utf-8")
    with pytest.raises(PlanError, match="not valid JSON"):
        load_template("ai-agent-security")


def test_render_value_substitution_rules():
    v = {"gw": "HQ-GW", "targets": ["m1", "m2"], "on": True, "ai.enable": "ai-agent-security"}
    assert render_value("{targets}", v) == ["m1", "m2"]          # whole string keeps the type
    assert render_value("{on}", v) is True
    assert render_value("on {gw} ({targets})", v) == "on HQ-GW (m1, m2)"
    assert render_value({"{ai.enable}": "{on}"}, v) == {"ai-agent-security": True}
    assert render_value({"literal {braces": "x {y"}, v) == {"literal {braces": "x {y"}
    with pytest.raises(PlanError, match="unknown variable"):
        render_value("{nope}", v)
    key = guard_key()
    real = render_value({"k": "{secret:lakera_api_key}"}, v, {"lakera_api_key": key})
    shown = render_value({"k": "{secret:lakera_api_key}"}, v, {"lakera_api_key": key}, display=True)
    assert real == {"k": key} and shown == {"k": "****" + key[-4:]}
    assert key not in redact.redact("value " + key)              # registered for redaction
    with pytest.raises(PlanError, match="Guard"):
        render_value("{secret:lakera_api_key}", v, {})


def test_client_host_name():
    assert client_host_name("10.1.1.50") == HOST
    assert client_host_name("fe80::1") == "aiguard-client-fe80--1"


# --------------------------------------------------------------------------- build


def test_build_plan_is_read_only_and_display_safe(connect, runlog):
    srv, client = connect()
    key = guard_key()
    plan = build_plan(client, opts(moderation=True), secrets={"lakera_api_key": key}, log=runlog)
    assert read_only_calls(srv) == []
    assert "show-package" in srv.call_names() and "show-threat-rule" in srv.call_names()
    assert [(s.id, s.action, s.command) for s in plan.steps] == [
        ("client_host", "add", "add-host"), ("profile", "add", "add-threat-profile"),
        ("rule", "add", "add-threat-rule"), ("publish", "publish", "publish"),
        ("install", "install", "install-policy"), ("moderation", "script", "run-script")]
    assert re.fullmatch(r"[0-9a-f]{12}", plan.plan_id) and plan.plan_id == compute_plan_id(plan)
    assert plan.package == "Standard" and plan.threat_layer == LAYER
    assert plan.protected_scope == HOST and plan.client_host_name == HOST
    assert plan.field_variant == "ai-agent-security" and plan.warnings == []

    prof = plan.step("profile")
    assert prof.payload["ai-agent-security-api-key"] == key            # real value, memory only
    assert prof.display_payload["ai-agent-security-api-key"] == "****" + key[-4:]
    assert prof.display_payload["ai-agent-security"] is True
    assert prof.display_payload["ai-agent-security-settings"] == {"project-id": "proj-demo"}
    assert prof.secret_keys == ["lakera_api_key"] and key not in repr(prof)
    rule = plan.step("rule").display_payload
    assert rule == {"layer": LAYER, "position": "top", "name": "AI Guard Demo", "action": "AIGuard-Demo",
                    "protected-scope": HOST, "track": "Log", "install-on": "HQ-GW", "comments": MARK}
    assert plan.step("moderation").payload["targets"] == ["HQ-GW"]
    assert plan.step("install").payload == {"policy-package": "Standard", "targets": ["HQ-GW"],
                                            "access": False, "threat-prevention": True}

    d = json.dumps(plan.to_dict())
    calls = plan.api_calls()
    assert key not in d and key not in json.dumps(calls) and key not in repr(plan)
    assert [c["command"] for c in calls] == ["add-host", "add-threat-profile", "add-threat-rule",
                                             "publish", "install-policy", "run-script"]
    assert key not in log_text(runlog)

    # stable for identical input, different when any payload changes
    again = build_plan(client, opts(moderation=True), secrets={"lakera_api_key": key}, log=runlog)
    assert again.plan_id == plan.plan_id
    other = build_plan(client, opts(moderation=True, rule_name="Other"), secrets={"lakera_api_key": key},
                       log=runlog)
    assert other.plan_id != plan.plan_id
    other_key = build_plan(client, opts(moderation=True), secrets={"lakera_api_key": guard_key()},
                           log=runlog)
    assert other_key.plan_id != plan.plan_id
    assert build_plan(client, opts(), secrets={"lakera_api_key": key}, log=runlog).plan_id != plan.plan_id
    assert read_only_calls(srv) == []


def test_build_uses_gateway_info_and_scope_variants(connect, runlog):
    from aiguard.gateways import discover

    srv, client = connect()
    gw = discover(client)[0]
    srv.seed_object("host", "Lab-PCs", ipv4_address="10.1.1.0", comments="lab")
    srv.reset_calls()
    key = guard_key()
    plan = build_plan(client, opts(scope="any"), secrets={"lakera_api_key": key}, log=runlog,
                      gateway_info=gw)
    assert "show-gateways-and-servers" not in srv.call_names()
    assert plan.step("client_host") is None and plan.protected_scope == "Any"
    assert plan.step("rule").display_payload["protected-scope"] == "Any"
    plan = build_plan(client, opts(scope="Lab-PCs", client_ip=None), secrets={"lakera_api_key": key},
                      log=runlog)
    assert plan.step("rule").display_payload["protected-scope"] == "Lab-PCs"
    for cmd in ("show-network", "show-group", "show-address-range", "show-group-with-exclusion",
                "show-security-zone", "show-dynamic-object"):
        srv.commands.discard(cmd)
    client._commands = None  # forget the cached show-commands reply
    with pytest.raises(PlanError) as ei:
        build_plan(client, opts(scope="No-Such-Object"), secrets={"lakera_api_key": key}, log=runlog)
    assert ei.value.code == "plan.scope_not_found"
    with pytest.raises(PlanError, match="IP address is unknown") as ei:
        build_plan(client, opts(client_ip=None), secrets={"lakera_api_key": key}, log=runlog)
    assert "--scope any" in " ".join(ei.value.fix)
    assert read_only_calls(srv) == []


def test_build_requires_key_project_and_known_gateway(connect, runlog):
    srv, client = connect()
    with pytest.raises(PlanError) as ei:
        build_plan(client, opts(), secrets={}, log=runlog)
    assert ei.value.code == "plan.missing_secret" and "Guard API key" in " ".join(ei.value.fix)
    with pytest.raises(PlanError, match="project ID"):
        build_plan(client, opts(lakera_project_id=None), secrets={"lakera_api_key": guard_key()},
                   log=runlog)
    with pytest.raises(PlanError) as ei:
        build_plan(client, opts(gateway="NOPE"), secrets={"lakera_api_key": guard_key()}, log=runlog)
    assert ei.value.code == "plan.gateway_not_found" and "HQ-GW" in ei.value.why
    with pytest.raises(PlanError, match="track"):
        build_plan(client, opts(track="Loud"), secrets={"lakera_api_key": guard_key()}, log=runlog)
    assert read_only_calls(srv) == []


def test_package_resolution(connect, runlog):
    gw = make_gateway("HQ-GW", "10.1.1.111", access_policy=None, threat_policy=None)
    srv, client = connect(gateways=[gw], packages=("Standard", "Lab"))
    key = guard_key()
    with pytest.raises(PlanError) as ei:
        build_plan(client, opts(), secrets={"lakera_api_key": key}, log=runlog)
    assert ei.value.code == "plan.package_unknown" and "--package" in ei.value.fix[0]
    plan = build_plan(client, opts(package="Lab"), secrets={"lakera_api_key": key}, log=runlog)
    assert plan.package == "Lab" and plan.threat_layer == "Lab Threat Prevention"
    with pytest.raises(PlanError) as ei:
        build_plan(client, opts(package="Missing"), secrets={"lakera_api_key": key}, log=runlog)
    assert ei.value.code == "plan.package_not_found"


def test_apply_without_install(connect, runlog, state):
    srv, client = connect()
    plan = build_plan(client, opts(install=False), secrets={"lakera_api_key": guard_key()}, log=runlog)
    assert plan.step("install") is None
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert result.ok and result.published and not result.installed
    assert "install-policy" not in srv.call_names() and "did not install" in result.message
    assert state.get_rollback(result.rollback_id)["status"] == "published"
    rb = rollback(client, result.rollback_id, install=False, log=runlog, state=state)
    assert rb.ok and not rb.installed and "install-policy" not in srv.call_names()


def test_package_from_only_package(connect, runlog):
    gw = make_gateway("HQ-GW", "10.1.1.111", access_policy=None, threat_policy=None)
    srv, client = connect(gateways=[gw])
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    assert plan.package == "Standard" and "show-packages" in srv.call_names()


@pytest.mark.parametrize("scenario", ["old_version", "ai_unsupported"])
def test_no_ai_support_is_a_plan_error(connect, runlog, scenario):
    srv, client = connect(scenario=scenario)
    assert not ({"test-ai-agent-security-api-key", "test-ai-guard-api-key"} & set(srv.commands))
    with pytest.raises(PlanError) as ei:
        build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    err = ei.value
    assert err.what == "This management server has no AI Agent Security support"
    assert err.why.startswith("Needs R82.20 management (API 2.2); server reports API ")
    if scenario == "old_version":
        assert "API 2 (R82)" in err.why
    assert err.state == "Nothing was changed." and read_only_calls(srv) == []


def test_old_gateway_is_a_plan_error(connect, runlog):
    srv, client = connect(gateways=[make_gateway("HQ-GW", "10.1.1.111", version="R82.10")])
    with pytest.raises(PlanError) as ei:
        build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    assert ei.value.code == "plan.gateway_version" and "R82.20" in ei.value.what


def test_ai_guard_field_variant(connect, runlog, state):
    srv, client = connect(scenario="ai_guard_names")
    key = guard_key()
    plan = build_plan(client, opts(), secrets={"lakera_api_key": key}, log=runlog)
    assert plan.field_variant == "ai-guard"
    shown = plan.step("profile").display_payload
    assert shown["ai-guard"] is True and shown["ai-guard-settings"] == {"project-id": "proj-demo"}
    assert shown["ai-guard-api-key"] == "****" + key[-4:] and "ai-agent-security" not in shown
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert result.ok, result.error and result.error.to_dict()
    assert srv.find("threat-profile", "AIGuard-Demo")["_secret"] == key


def test_name_conflict_with_foreign_objects(connect, runlog):
    srv, client = connect()
    key = guard_key()
    srv.seed_object("threat-profile", "AIGuard-Demo", comments="Bob's profile")
    with pytest.raises(PlanError) as ei:
        build_plan(client, opts(), secrets={"lakera_api_key": key}, log=runlog)
    err = ei.value
    assert err.code == "plan.name_conflict" and err.what == "An object named AIGuard-Demo already exists"
    assert "--profile-name" in err.fix[0] and err.state == "Nothing was changed."
    plan = build_plan(client, opts(profile_name="AIGuard-Demo-2"), secrets={"lakera_api_key": key},
                      log=runlog)
    assert plan.step("profile").action == "add"

    srv.seed_object("threat-rule", "AI Guard Demo", layer=LAYER, action="Optimized", comments="")
    with pytest.raises(PlanError) as ei:
        build_plan(client, opts(profile_name="AIGuard-Demo-2"), secrets={"lakera_api_key": key},
                   log=runlog)
    assert "AI Guard Demo" in ei.value.what and "--rule-name" in ei.value.fix[0]

    srv.seed_object("host", HOST, ipv4_address=CLIENT_IP, comments="someone else's")
    with pytest.raises(PlanError) as ei:
        build_plan(client, opts(profile_name="AIGuard-Demo-2", rule_name="Other"),
                   secrets={"lakera_api_key": key}, log=runlog)
    assert HOST in ei.value.what and "--scope" in " ".join(ei.value.fix)
    assert read_only_calls(srv) == []


def test_unsupported_command_becomes_manual(connect, runlog, state):
    srv, client = connect()
    srv.commands.discard("run-script")
    client._commands = None
    plan = build_plan(client, opts(moderation=True), secrets={"lakera_api_key": guard_key()}, log=runlog)
    mod = plan.step("moderation")
    assert mod.action == "manual" and any(CONFP in m for m in mod.manual_steps)
    assert "run-script" not in [c["command"] for c in plan.api_calls()]
    assert any("moderation" in w for w in plan.warnings)
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert result.ok and result.installed and mod.status == "manual"
    assert result.moderation_enabled is False and "run-script" not in srv.call_names()
    assert any("moderation" in w for w in result.warnings)


# --------------------------------------------------------------------------- apply


def test_apply_happy_path_with_moderation(connect, runlog, state, aiguard_home):
    srv, client = connect()
    key = guard_key()
    proj = project_id()
    plan = build_plan(client, opts(moderation=True, lakera_project_id=proj),
                      secrets={"lakera_api_key": key}, log=runlog)
    srv.reset_calls()
    events = []
    points_at_publish = []

    def progress(step_id, status, pct, message):
        events.append((step_id, status, pct, message))
        if step_id == "publish" and status == "running" and not points_at_publish:
            points_at_publish.append([(p["status"], len(p["objects"])) for p in state.list_rollbacks()])
            assert not srv.state.published

    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state,
                        progress_cb=progress)
    assert result.ok, result.error and result.error.to_dict()
    assert points_at_publish == [[("recorded", 3)]]   # saved BEFORE publish
    assert result.published and result.installed and result.moderation_enabled is True
    assert re.fullmatch(r"[0-9a-f]{6}", result.rollback_id)
    assert names(srv) == ["add-host", "add-threat-profile", "show-threat-profile", "add-threat-rule",
                          "publish", "install-policy", "run-script"]
    assert [s.status for s in result.steps] == ["done"] * 6
    assert "aiguard rollback %s" % result.rollback_id in result.message

    host = srv.find("host", HOST)
    assert host["ipv4-address"] == CLIENT_IP and host["comments"] == MARK
    prof = srv.find("threat-profile", "AIGuard-Demo")
    assert prof["ai-agent-security"] is True and prof["_secret"] == key
    assert prof["ai-agent-security-settings"] == {"project-id": proj}
    assert prof["threat-emulation"] is False and prof["confidence-level-low"] == "Detect"
    rule = srv.find("threat-rule", "AI Guard Demo")
    assert srv.state.rulebases[LAYER][0] == "AI Guard Demo"
    assert rule["action"]["name"] == "AIGuard-Demo" and rule["protected-scope"][0]["name"] == HOST
    assert rule["install-on"][0]["name"] == "HQ-GW" and rule["track"]["name"] == "Log"
    assert srv.state.published and srv.state.installs[-1] == {
        "policy-package": "Standard", "targets": ["HQ-GW"], "access": False, "threat-prevention": True}
    assert srv.state.moderation == {"HQ-GW": True}
    assert srv.state.scripts[0]["script-type"] == "one time" and CONFP in srv.state.scripts[0]["script"]

    point = state.get_rollback(result.rollback_id)
    assert point["status"] == "installed" and point["plan_id"] == plan.plan_id
    assert point["server"] == "127.0.0.1" and point["gateway"] == "HQ-GW" and point["package"] == "Standard"
    by_step = {o["step"]: o for o in point["objects"]}
    assert by_step["client_host"]["uid"] == host["uid"]
    assert by_step["profile"]["uid"] == prof["uid"] and by_step["rule"]["uid"] == rule["uid"]
    assert by_step["rule"]["rollback"] == {"command": "delete-threat-rule",
                                          "payload": {"layer": LAYER, "name": "AI Guard Demo"}}
    assert by_step["moderation"]["rollback"]["command"] == "run-script"
    assert "-v false" in by_step["moderation"]["rollback"]["payload"]["script"]

    seen = {(e[0], e[1]) for e in events}
    assert ("profile", "running") in seen and ("install", "done") in seen and ("moderation", "done") in seen
    assert any(e[0] == "install" and isinstance(e[2], int) for e in events)
    # the AI Agent Security key is nowhere: plan display, result, progress, logs, state
    blob = json.dumps([plan.to_dict(), plan.api_calls(), result.to_dict(), [list(e) for e in events]])
    assert key not in blob
    assert key not in log_text(runlog)
    assert key not in (aiguard_home / "state.json").read_text(encoding="utf-8")

    with pytest.raises(PlanError, match="already applied"):
        apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)


def test_plan_id_mismatch_and_tampering(connect, runlog, state):
    srv, client = connect()
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    srv.reset_calls()
    with pytest.raises(ApprovalError) as ei:
        apply_plan(client, plan, approved_plan_id="000000000000", log=runlog, state=state)
    assert plan.plan_id in ei.value.fix[0] and ei.value.state == "Nothing was changed."
    plan.step("rule").display_payload["protected-scope"] = "Any"   # changed after approval
    with pytest.raises(ApprovalError, match="changed"):
        apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert srv.call_names() == [] and state.list_rollbacks() == []


def test_install_fails_keeps_rollback_point(connect, runlog, state):
    srv, client = connect(scenario="install_fails")
    plan = build_plan(client, opts(moderation=True), secrets={"lakera_api_key": guard_key()}, log=runlog)
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert not result.ok and result.published and not result.installed
    rid = result.rollback_id
    assert rid and state.get_rollback(rid)["status"] == "published"
    assert state.get_rollback(rid)["install_error"]
    err = result.error
    assert re.fullmatch(r"Published 3 objects\. Nothing was installed on HQ-GW: the gateway keeps "
                        r"enforcing its previous Threat Prevention policy \(installed \S+\) until "
                        r"an install succeeds\. Undo: aiguard rollback %s" % rid, err.state), err.state
    assert result.state_text == err.state
    assert result.install_status == {"threat_prevention": "not installed"}
    assert state.get_rollback(rid)["install_status"] == {"threat_prevention": "not installed"}
    assert err.details["action"] == {"id": "rollback", "rollback_id": rid,
                                     "cli": "aiguard rollback %s" % rid}
    assert err.fix[0].startswith("AI Agent Security needs R82.20 on the gateway")
    assert "not supported" in (err.server_said or "")
    assert any("aiguard rollback %s" % rid in f for f in err.fix)
    assert plan.step("install").status == "failed" and plan.step("moderation").status == "skipped"
    assert srv.state.scripts == [] and "discard" not in srv.call_names()
    assert err.log_line and err.log_line > 0


def test_locked_discards_and_publishes_nothing(connect, runlog, state):
    srv, client = connect(scenario="locked")
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert not result.ok and not result.published and not result.installed
    assert result.error.code == "mgmt.object_locked"
    assert result.error.state.startswith("Nothing was changed.")
    assert "discard" in srv.call_names() and "publish" not in srv.call_names()
    assert srv.state.discards == 1 and not srv.state.published
    assert srv.find("host", HOST) is None and srv.find("threat-profile", "AIGuard-Demo") is None
    assert [s.status for s in result.steps] == ["done", "done", "failed", "skipped", "skipped"]
    assert state.list_rollbacks() == [] and result.rollback_id is None


def test_publish_fails_discards_and_marks_point(connect, runlog, state):
    srv, client = connect(scenario="publish_fails")
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert not result.ok and not result.published
    assert result.error.state.startswith("Nothing was changed.")
    assert "discard" in srv.call_names() and plan.step("publish").status == "failed"
    points = state.list_rollbacks()
    assert len(points) == 1 and points[0]["status"] == "discarded" and result.rollback_id is None
    rb = rollback(client, points[0]["id"], log=runlog, state=state)
    assert rb.ok and "discarded" in rb.message


def test_connection_lost_during_publish_keeps_rollback_point(connect, runlog, state, monkeypatch):
    from aiguard.errors import ConnectError

    srv, client = connect()
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    real_publish = client.publish

    def publish_then_drop(progress_cb=None):
        real_publish(progress_cb=progress_cb)          # it went through ...
        raise ConnectError("Connection to the management server was lost")  # ... but we never heard

    monkeypatch.setattr(client, "publish", publish_then_drop)
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert not result.ok and srv.state.published
    rid = result.rollback_id
    assert rid and "may or may not" in result.error.state and "aiguard rollback %s" % rid in result.error.state
    assert state.get_rollback(rid)["status"] == "publish-unknown"   # not "discarded": undoable
    assert state.latest_rollback(server=client.server)["id"] == rid
    monkeypatch.setattr(client, "publish", real_publish)
    rb = rollback(client, rid, log=runlog, state=state)
    assert rb.ok and srv.find("threat-profile", "AIGuard-Demo") is None


def test_script_denied(connect, runlog, state):
    srv, client = connect(scenario="script_denied")
    plan = build_plan(client, opts(moderation=True), secrets={"lakera_api_key": guard_key()}, log=runlog)
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    # The policy is published and installed: a script the user does by hand is a warning
    # with its five fields (spec 4.1 "You do this"), not a failed apply.
    assert result.ok and result.error is None and result.published and result.installed
    mod = plan.step("moderation")
    assert result.moderation_enabled is False and mod.status == "manual"   # "You do this"
    assert "Run One Time Script" in mod.message
    assert len(result.notices) == 1
    err = result.notices[0]
    assert err["code"] == "plan.script_permission" and err["what"] == "Content moderation was not turned on"
    assert "Run One Time Script" in err["why"] and any("Run One Time Script" in f for f in err["fix"])
    assert any(CONFP in f and f.endswith("-v true") for f in err["fix"])
    assert "aiguard rollback %s" % result.rollback_id in err["state"]
    assert "Run one time script permission is required" in err["server_said"]
    assert any(w.startswith("Content moderation was not turned on") for w in result.warnings)
    assert "Still to do: Content moderation was not turned on" in result.message
    point = state.get_rollback(result.rollback_id)
    assert point["status"] == "installed"
    # the script did not run: no undo entry for it
    assert [o["step"] for o in point["objects"]] == ["client_host", "profile", "rule"]
    assert result.to_dict()["notices"][0]["code"] == "plan.script_permission"


def test_update_of_our_existing_objects(connect, runlog, state):
    srv, client = connect()
    old_key, key = guard_key(), guard_key()
    srv.seed_object("host", HOST, ipv4_address=CLIENT_IP, comments=MARK)
    srv.seed_object("threat-profile", "AIGuard-Demo", comments=MARK, ai_agent_security=True,
                    api_key=old_key, ai_agent_security_settings={"project-id": "old-project"})
    srv.seed_object("threat-rule", "AI Guard Demo", layer=LAYER, position="top", action="AIGuard-Demo",
                    protected_scope=HOST, install_on="HQ-GW", track="None", comments=MARK)
    srv.reset_calls()
    plan = build_plan(client, opts(lakera_project_id="new-project"), secrets={"lakera_api_key": key},
                      log=runlog)
    assert read_only_calls(srv) == []
    assert [(s.id, s.action, s.command) for s in plan.steps[:3]] == [
        ("client_host", "update", "set-host"), ("profile", "update", "set-threat-profile"),
        ("rule", "update", "set-threat-rule")]
    assert "position" not in plan.step("rule").display_payload
    assert plan.step("rule").display_payload["name"] == "AI Guard Demo"
    assert plan.step("profile").existing_uid == srv.find("threat-profile", "AIGuard-Demo")["uid"]
    srv.reset_calls()
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert result.ok, result.error and result.error.to_dict()
    assert not [c for c in srv.call_names() if c.startswith("add-")]
    assert names(srv)[:3] == ["set-host", "set-threat-profile", "set-threat-rule"]
    prof = srv.find("threat-profile", "AIGuard-Demo")
    assert prof["_secret"] == key and prof["ai-agent-security-settings"] == {"project-id": "new-project"}
    assert srv.find("threat-rule", "AI Guard Demo")["track"]["name"] == "Log"
    point = state.get_rollback(result.rollback_id)
    assert {o["step"]: o["uid"] for o in point["objects"]} == {
        "client_host": srv.find("host", HOST)["uid"], "profile": prof["uid"],
        "rule": srv.find("threat-rule", "AI Guard Demo")["uid"]}


def test_read_only_session(connect, runlog, state):
    srv, client = connect(read_only=True)
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    assert any("read-only" in w for w in plan.warnings)
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert not result.ok and result.error.code == "plan.read_only"
    assert read_only_calls(srv) == []


def test_cluster_targets_members(connect, runlog, state):
    srv, client = connect(with_cluster=True, scenario="script_tasks_only")
    plan = build_plan(client, opts(gateway="LAB-CL", client_ip="10.2.2.50", moderation=True),
                      secrets={"lakera_api_key": guard_key()}, log=runlog)
    assert plan.is_cluster and plan.step("moderation").payload["targets"] == ["LAB-CL-m1", "LAB-CL-m2"]
    assert plan.step("install").payload["targets"] == ["LAB-CL"]
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert result.ok, result.error and result.error.to_dict()
    assert srv.state.moderation == {"LAB-CL-m1": True, "LAB-CL-m2": True}
    assert srv.state.installs[-1]["targets"] == ["LAB-CL"]


# --------------------------------------------------------------------------- rollback


def test_rollback_happy_path_and_idempotent(connect, runlog, state):
    srv, client = connect()
    plan = build_plan(client, opts(moderation=True), secrets={"lakera_api_key": guard_key()}, log=runlog)
    applied = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert applied.ok
    srv.reset_calls()
    events = []
    result = rollback(client, applied.rollback_id, log=runlog, state=state,
                      progress_cb=lambda *a: events.append(a))
    assert result.ok, result.error and result.error.to_dict()
    assert result.kind == "rollback" and result.published and result.installed
    assert names(srv) == ["run-script", "delete-threat-rule", "delete-threat-profile", "delete-host",
                          "publish", "install-policy"]
    assert "uid" in srv.last_call("delete-threat-rule") and srv.last_call("delete-threat-rule")["layer"] == LAYER
    assert srv.last_call("install-policy")["access"] is False
    assert srv.last_call("install-policy")["threat-prevention"] is True
    assert srv.find("host", HOST) is None and srv.find("threat-profile", "AIGuard-Demo") is None
    assert srv.state.rulebases[LAYER] == [] and srv.state.moderation == {"HQ-GW": False}
    point = state.get_rollback(applied.rollback_id)
    assert point["status"] == "rolled-back" and point["rolled_back_at"]
    assert state.latest_rollback("127.0.0.1") is None
    assert ("undo-rule", "done") in {(e[0], e[1]) for e in events}

    srv.reset_calls()
    again = rollback(client, applied.rollback_id, log=runlog, state=state)
    assert again.ok and "already rolled back" in again.message and srv.call_names() == []


def test_rollback_skips_objects_already_gone(connect, runlog, state):
    srv, client = connect()
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    applied = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert applied.ok
    # someone removes the demo objects by hand
    client.call("delete-threat-rule", {"layer": LAYER, "name": "AI Guard Demo"})
    client.wait_task(client.call("delete-threat-profile", {"name": "AIGuard-Demo"})["task-id"], what="x")
    client.call("delete-host", {"name": HOST})
    client.publish()
    srv.reset_calls()
    result = rollback(client, applied.rollback_id, log=runlog, state=state)
    assert result.ok and not result.published and result.installed
    assert [s.status for s in result.steps] == ["skipped", "skipped", "skipped", "skipped", "done"]
    assert all(s.message == "Already gone" for s in result.steps[:3])
    assert "publish" not in srv.call_names()
    assert state.get_rollback(applied.rollback_id)["status"] == "rolled-back"


def test_rollback_by_name_keeps_foreign_objects(connect, runlog, state):
    srv, client = connect()
    srv.seed_object("threat-profile", "Shared-Profile", comments="Bob's profile")
    rid = state.add_rollback({
        "kind": "plan", "plan_id": "abc", "server": "127.0.0.1", "domain": None, "gateway": "HQ-GW",
        "package": "Standard", "install": {"access": False, "threat_prevention": True},
        "objects": [{"step": "profile", "kind": "add", "command": "add-threat-profile", "uid": None,
                     "describe": "Delete threat profile Shared-Profile",
                     "rollback": {"command": "delete-threat-profile", "payload": {"name": "Shared-Profile"}},
                     "probe": {"command": "show-threat-profile", "payload": {"name": "Shared-Profile"}}}]})
    result = rollback(client, rid, install=False, log=runlog, state=state)
    assert result.ok and srv.find("threat-profile", "Shared-Profile") is not None
    assert "not created by AI Guard Demo Kit" in result.steps[0].message
    assert "delete-threat-profile" not in srv.call_names()


def test_rollback_errors(connect, runlog, state):
    srv, client = connect()
    with pytest.raises(PlanError) as ei:
        rollback(client, "ffffff", log=runlog, state=state)
    assert ei.value.code == "plan.rollback_not_found"
    rid = state.add_rollback({"kind": "plan", "server": "10.9.9.9", "gateway": "HQ-GW",
                              "package": "Standard", "objects": []})
    with pytest.raises(PlanError) as ei:
        rollback(client, rid, log=runlog, state=state)
    assert ei.value.code == "plan.rollback_wrong_server" and "10.9.9.9" in ei.value.fix[0]
    assert srv.call_names() == []


def test_rollback_keeps_host_still_in_use(connect, runlog, state):
    gw = make_gateway("HQ-GW", "10.1.1.111", https_inspection=False,
                      interfaces=[("eth0", "10.1.1.111", 24), ("eth1", "198.51.100.111", 24)])
    srv, client = connect(gateways=[gw])
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    first = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    https = build_plan(client, opts(template="https-inspection", add_https_rule=True), log=runlog)
    assert https.step("client_host").action == "update"     # ours, from the first plan
    second = apply_plan(client, https, approved_plan_id=https.plan_id, log=runlog, state=state)
    assert first.ok and second.ok
    result = rollback(client, first.rollback_id, log=runlog, state=state)
    assert result.ok, result.error and result.error.to_dict()
    host_step = [s for s in result.steps if s.id == "undo-client_host"][0]
    assert host_step.status == "skipped" and host_step.message.startswith("Kept: still in use")
    assert srv.find("host", HOST) is not None and srv.find("threat-profile", "AIGuard-Demo") is None
    assert any("still in use" in w for w in result.warnings)


# --------------------------------------------------------------------------- HTTPS Inspection template


def test_https_template_happy_path_and_rollback(connect, runlog, state):
    gw = make_gateway("HQ-GW", "10.1.1.111", https_inspection=False,
                      interfaces=[("eth0", "10.1.1.111", 24), ("eth1", "198.51.100.111", 24)])
    srv, client = connect(gateways=[gw])
    plan = build_plan(client, opts(template="https-inspection", add_https_rule=True,
                                   lakera_project_id=None), log=runlog)
    assert read_only_calls(srv) == [] and "show-outbound-inspection-certificate" in srv.call_names()
    assert [(s.id, s.action, s.command) for s in plan.steps] == [
        ("https_gateway", "update", "set-simple-gateway"), ("client_host", "add", "add-host"),
        ("https_rule", "add", "add-https-rule"), ("publish", "publish", "publish"),
        ("install", "install", "install-policy")]
    assert plan.https_layer == "Default Outbound Layer" and plan.threat_layer is None
    assert plan.step("https_gateway").display_payload == {
        "name": "HQ-GW", "enable-https-inspection": True,
        "https-inspection": {"deployment-mode": "full"}}       # API 2+: Full mode
    rule = plan.step("https_rule").display_payload
    assert rule == {"layer": "Default Outbound Layer", "position": "top", "name": "AI Guard Demo inspect",
                    "source": HOST, "destination": "Any", "service": "Any", "action": "Inspect",
                    "track": "Log", "install-on": "HQ-GW", "comments": MARK}
    assert "blade" not in rule
    assert plan.step("install").payload["access"] is True
    assert plan.step("install").payload["threat-prevention"] is True

    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert result.ok, result.error and result.error.to_dict()
    assert srv.gateway("HQ-GW")["enable-https-inspection"] is True
    assert srv.gateway("HQ-GW")["https-inspection"]["deployment-mode"] == "full"
    assert srv.state.rulebases["Default Outbound Layer"] == ["AI Guard Demo inspect"]
    assert srv.state.installs[-1] == {"policy-package": "Standard", "targets": ["HQ-GW"],
                                      "access": True, "threat-prevention": True}
    srv.reset_calls()
    rb = rollback(client, result.rollback_id, log=runlog, state=state)
    assert rb.ok, rb.error and rb.error.to_dict()
    assert names(srv) == ["delete-https-rule", "delete-host", "set-simple-gateway", "publish",
                          "install-policy"]
    assert srv.last_call("set-simple-gateway") == {"name": "HQ-GW", "enable-https-inspection": False}
    assert srv.last_call("install-policy")["access"] is True
    assert srv.gateway("HQ-GW")["enable-https-inspection"] is False
    assert srv.state.rulebases["Default Outbound Layer"] == []


def test_https_already_on_changes_nothing(connect, runlog, state):
    srv, client = connect()
    plan = build_plan(client, opts(template="https-inspection", lakera_project_id=None), log=runlog)
    assert [(s.id, s.action) for s in plan.steps] == [("https_gateway", "none"), ("publish", "publish"),
                                                     ("install", "install")]
    srv.reset_calls()
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert result.ok and not result.published and result.installed and result.rollback_id is None
    assert names(srv) == ["install-policy"] and state.list_rollbacks() == []
    assert plan.step("https_gateway").status == "skipped"


def test_https_off_without_outbound_ca_is_a_plan_error(connect, runlog):
    srv, client = connect(scenario="https_off")
    with pytest.raises(PlanError) as ei:
        build_plan(client, opts(template="https-inspection"), log=runlog)
    err = ei.value
    assert err.what == "No outbound inspection certificate" and err.code == "plan.no_outbound_ca"
    assert err.fix[0] == ("SmartConsole > HQ-GW > HTTPS Inspection > Step 1: create or import the "
                          "outbound CA")
    assert err.state == "Nothing was changed." and read_only_calls(srv) == []


def test_https_cluster_uses_set_simple_cluster(connect, runlog, state):
    cluster = make_cluster("LAB-CL", "10.2.2.100", [("LAB-CL-m1", "10.2.2.101"), ("LAB-CL-m2", "10.2.2.102")],
                           https_inspection=False)
    srv, client = connect(gateways=[make_gateway("HQ-GW", "10.1.1.111"), cluster])
    plan = build_plan(client, opts(gateway="LAB-CL", template="https-inspection"), log=runlog)
    assert plan.step("https_gateway").command == "set-simple-cluster"
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert result.ok, result.error and result.error.to_dict()
    assert srv.gateway("LAB-CL")["enable-https-inspection"] is True
    assert "show-task" in srv.call_names()   # set-simple-cluster is asynchronous


def test_https_layer_on_r81_20_singular_field(connect, runlog, state):
    gw = make_gateway("HQ-GW", "10.1.1.111", version="R81.20", https_inspection=False)
    srv, client = connect(api_version="1.9.1", gateways=[gw])
    plan = build_plan(client, opts(template="https-inspection", add_https_rule=True, scope="any"),
                      log=runlog)
    assert plan.https_layer == "Default Layer"
    rule = plan.step("https_rule")
    assert rule.display_payload["source"] == "Any"
    # API 1.9.1 identifies HTTPS rules by uid / rule number only: the rule is a manual step
    # (no show-https-rule by name, which the server would refuse)
    assert rule.action == "manual" and rule.manual_steps
    assert "show-https-rule" not in srv.call_names()
    assert any("needs Management API 2" in w and "1.9.1" in w for w in plan.warnings)
    # deployment-mode is an API 2 field: not sent to 1.9.1
    assert plan.step("https_gateway").display_payload == {"name": "HQ-GW",
                                                          "enable-https-inspection": True}
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert result.ok, result.error and result.error.to_dict()
    assert srv.gateway("HQ-GW")["enable-https-inspection"] is True
    assert srv.state.rulebases["Default Layer"] == []
    assert rule.status == "manual" and "https_rule" in " ".join(result.warnings)
    rb = rollback(client, result.rollback_id, log=runlog, state=state)
    assert rb.ok and srv.gateway("HQ-GW")["enable-https-inspection"] is False


def test_https_learning_mode_is_set_to_full(connect, runlog, state):
    srv, client = connect(scenario="https_learning")
    plan = build_plan(client, opts(template="https-inspection", lakera_project_id=None), log=runlog)
    gw_step = plan.step("https_gateway")
    assert gw_step.action == "update"          # on, but Learning mode: not "already in place"
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert result.ok and srv.gateway("HQ-GW")["https-inspection"]["deployment-mode"] == "full"
    again = build_plan(client, opts(template="https-inspection", lakera_project_id=None), log=runlog)
    assert again.step("https_gateway").action == "none"


# --------------------------------------------------------------------------- install outcome


def test_partial_install_reports_each_policy_type(connect, runlog, state):
    gw = make_gateway("HQ-GW", "10.1.1.111", https_inspection=False,
                      interfaces=[("eth0", "10.1.1.111", 24), ("eth1", "198.51.100.111", 24)])
    for status in ("failed", "partially succeeded"):
        srv, client = connect(gateways=[gw], scenario="partial_install_failed")
        srv.partial_install_status = status
        plan = build_plan(client, opts(template="https-inspection", lakera_project_id=None),
                          log=runlog)
        result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
        assert not result.ok and result.published and not result.installed
        assert result.install_status == {"access": "not installed", "threat_prevention": "installed"}
        err = result.error
        assert "nothing installed" not in err.state
        assert ("Threat Prevention was installed on HQ-GW; Access Control was NOT installed: the "
                "gateway keeps enforcing its previous Access Control policy (which carries the "
                "HTTPS Inspection settings) (installed ") in err.state, err.state
        assert "both Access Control and Threat Prevention must say Succeeded" in err.state
        assert LAB_DATA_TYPES_ERROR in err.server_said
        # the failing rule is not the kit's: say so, and name the real fix (sk116272)
        assert err.fix[0].startswith("The failing rule 2 (AI) in layer Network was not created by "
                                     "AI Guard Demo Kit")
        assert any("sk116272" in f and "Remove the data types" in f for f in err.fix)
        assert not any("upgrade it" in f for f in err.fix)       # the gateway is R82.20
        rid = result.rollback_id
        assert any("does not fix rule 2 (AI)" in f and rid in f for f in err.fix)
        assert state.get_rollback(rid)["install_status"]["access"] == "not installed"


def test_install_timeout_keeps_the_task_state(connect, runlog, state, monkeypatch):
    from aiguard.errors import MgmtApiError

    srv, client = connect()
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)

    def slow_install(*a, **k):
        raise MgmtApiError("Install policy did not finish within 1200s", code="mgmt.task_timeout",
                           command="install-policy", details={"install_submitted": True})

    monkeypatch.setattr(client, "install_policy", slow_install)
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert not result.ok and result.published
    assert "it may still finish" in result.error.state and "nothing installed" not in result.error.state
    assert result.install_status == {"threat_prevention": "unknown"}


def test_install_warnings_reach_the_result(connect, runlog, state, monkeypatch):
    srv, client = connect()
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    real = client.install_policy

    def install(*a, **k):
        res = real(*a, **k)
        res["warnings"] = ["Rule 3: a setting is not supported by the gateway and was skipped"]
        return res

    monkeypatch.setattr(client, "install_policy", install)
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert result.ok and result.installed
    assert ("Install warning: Rule 3: a setting is not supported by the gateway and was skipped"
            in result.warnings)
    assert "(with 1 warning)" in plan.step("install").message


def test_api_error_while_polling_publish_is_uncertain(connect, runlog, state, monkeypatch):
    from aiguard.errors import MgmtApiError

    srv, client = connect()
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    real_wait = client.wait_task

    def wait(task_id, **kw):
        if kw.get("what") == "publish":
            raise MgmtApiError("show-task failed on the management server (HTTP 500)",
                               code="mgmt.server_error", command="show-task", http_status=500)
        return real_wait(task_id, **kw)

    monkeypatch.setattr(client, "wait_task", wait)
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert not result.ok and srv.state.publish_count == 1   # the server committed it
    rid = result.rollback_id
    assert rid and "may or may not" in result.error.state
    assert state.get_rollback(rid)["status"] == "publish-unknown"
    monkeypatch.setattr(client, "wait_task", real_wait)
    assert state.latest_rollback(server=client.server)["id"] == rid
    rb = rollback(client, rid, log=runlog, state=state)
    assert rb.ok and srv.find("threat-profile", "AIGuard-Demo") is None


def test_publish_failure_fix_matches_the_discard(connect, runlog, state):
    srv, client = connect(scenario="publish_fails")
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    fix = result.error.fix
    assert not any("publish again" in f or "shows this session" in f for f in fix)
    assert fix[-1].startswith("Then apply the plan again: aiguard discarded")


# --------------------------------------------------------------------------- host with the same IP


def test_existing_host_with_the_client_ip_is_reused(connect, runlog, state):
    srv, client = connect()
    srv.seed_object("host", "win_client", ipv4_address=CLIENT_IP, comments="lab client")
    srv.reset_calls()
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    assert read_only_calls(srv) == [] and "show-objects" in srv.call_names()
    assert plan.step("client_host") is None and plan.client_host_name is None
    assert plan.protected_scope == "win_client"
    assert plan.step("rule").display_payload["protected-scope"] == "win_client"
    assert any("win_client already has this computer's address" in w for w in plan.warnings)
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert result.ok, result.error and result.error.to_dict()
    assert srv.find("host", HOST) is None
    rb = rollback(client, result.rollback_id, log=runlog, state=state)
    assert rb.ok and srv.find("host", "win_client") is not None   # not ours: left alone


def test_duplicate_ip_rejected_at_apply_names_the_scope_fix(connect, runlog, state):
    srv, client = connect()
    srv.seed_object("host", "win_client", ipv4_address=CLIENT_IP, comments="lab client")
    srv.commands.discard("show-objects")       # the lookup is not possible here
    client._commands = None
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    assert plan.step("client_host").action == "add"
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    err = result.error
    assert not result.ok and err.code == "mgmt.validation"
    assert "same IP address" in err.server_said
    assert err.fix[0].startswith("Another host object already has this IP address") and \
        "--scope" in err.fix[0] and "Protected scope" in err.fix[0]
    assert err.state == "Nothing was changed."


# --------------------------------------------------------------------------- gateway scripts


def test_script_with_unknown_result_keeps_its_undo(connect, runlog, state, monkeypatch):
    from aiguard.errors import ConnectError

    srv, client = connect()
    plan = build_plan(client, opts(moderation=True), secrets={"lakera_api_key": guard_key()},
                      log=runlog)
    real_wait = client.wait_task

    def wait(task_id, **kw):
        if kw.get("command") == "run-script":
            raise ConnectError("The management server did not answer")
        return real_wait(task_id, **kw)

    monkeypatch.setattr(client, "wait_task", wait)
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    assert result.ok and result.installed and srv.state.moderation == {"HQ-GW": True}
    assert result.moderation_enabled is None              # unknown, not "not turned on"
    assert result.notices[0]["what"].startswith("Content moderation may or may not be on")
    point = state.get_rollback(result.rollback_id)
    mod = [o for o in point["objects"] if o["step"] == "moderation"]
    assert mod and mod[0].get("uncertain") is True
    monkeypatch.setattr(client, "wait_task", real_wait)
    rb = rollback(client, result.rollback_id, log=runlog, state=state)
    assert rb.ok and srv.state.moderation == {"HQ-GW": False}


def test_interrupted_script_can_still_be_rolled_back(connect, runlog, state, monkeypatch):
    srv, client = connect()
    plan = build_plan(client, opts(moderation=True), secrets={"lakera_api_key": guard_key()},
                      log=runlog)
    real_wait = client.wait_task

    def wait(task_id, **kw):
        if kw.get("command") == "run-script":
            raise KeyboardInterrupt
        return real_wait(task_id, **kw)

    monkeypatch.setattr(client, "wait_task", wait)
    with pytest.raises(KeyboardInterrupt):
        apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    point = state.latest_rollback(server=client.server)
    mod = [o for o in point["objects"] if o["step"] == "moderation"]
    assert mod and mod[0]["pending"] is True               # recorded before it ran
    monkeypatch.setattr(client, "wait_task", real_wait)
    rb = rollback(client, point["id"], log=runlog, state=state)
    assert rb.ok and srv.state.moderation == {"HQ-GW": False}


def test_plan_dataclass_round_trip_fields():
    p = Plan(plan_id="", server="s", domain=None, gateway="g", package="p", threat_layer=None,
             steps=[], warnings=[], created_at="")
    assert compute_plan_id(p) == compute_plan_id(p) and len(compute_plan_id(p)) == 12
    assert p.to_dict()["steps"] == [] and p.api_calls() == []


def test_expired_session_mid_apply_does_not_claim_a_discard(connect, runlog, state):
    srv, client = connect()
    plan = build_plan(client, opts(), secrets={"lakera_api_key": guard_key()}, log=runlog)
    real_call = client.call

    def call(command, payload=None, **kw):
        if command == "add-threat-rule":
            srv.state.sessions.clear()      # the server dropped the session mid-way
        return real_call(command, payload, **kw)

    client.call = call
    result = apply_plan(client, plan, approved_plan_id=plan.plan_id, log=runlog, state=state)
    err = result.error
    assert not result.ok and err.code == "mgmt.session_expired"
    assert err.state.startswith("Nothing was published. aiguard could not discard")
    assert "View Sessions: discard the session aiguard-demo" in err.state
